#include "precomp.hxx"
#include "TrueTypeSubsetter\util2.cpp"
#include "TrueTypeSubsetter\truetype.cpp"

#include "DWriteWrapper\LocalizedErrorMsgs.cpp"
#include "DWriteWrapper\DWriteTypeConverter.cpp"
#include "DWriteWrapper\Factory.cpp"
#include "DWriteWrapper\Font.cpp"
#include "DWriteWrapper\FontCollection.cpp"
#include "DWriteWrapper\FontFace.cpp"
#include "DWriteWrapper\FontFamily.cpp"
#include "DWriteWrapper\FontFile.cpp"
#include "DWriteWrapper\FontList.cpp"
#include "DWriteWrapper\LocalizedStrings.cpp"
#include "DWriteWrapper\NativePointerWrapper.cpp"

#include "DWriteWrapper\FontCollectionLoader.cpp"
#include "DWriteWrapper\FontFileEnumerator.cpp"
#include "DWriteWrapper\FontFileLoader.cpp"
#include "DWriteWrapper\FontFileStream.cpp"

#include "DWriteWrapper\TextItemizer.cpp"
#include "DWriteWrapper\TextAnalyzer.cpp"
#include "DWriteWrapper\DWriteFontFeature.h"

#include "DWriteWrapper\ItemSpan.cpp"
#include "DWriteWrapper\ItemProps.cpp"
#include "DWriteWrapper\ItemizerHelper.h"
#include "DWriteWrapper\IClassification.h"
