

/* this ALWAYS GENERATED file contains the definitions for the interfaces */


 /* File created by MIDL compiler version 8.00.0601 */
/* @@MIDL_FILE_HEADING(  ) */

#pragma warning( disable: 4049 )  /* more than 64k source lines */


/* verify that the <rpcndr.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif

/* verify that the <rpcsal.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCSAL_H_VERSION__
#define __REQUIRED_RPCSAL_H_VERSION__ 100
#endif

#include "rpc.h"
#include "rpcndr.h"

#ifndef __RPCNDR_H_VERSION__
#error this stub requires an updated version of <rpcndr.h>
#endif // __RPCNDR_H_VERSION__

#ifndef COM_NO_WINDOWS_H
#include "windows.h"
#include "ole2.h"
#endif /*COM_NO_WINDOWS_H*/

#ifndef __vslog_h__
#define __vslog_h__

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

/* Forward Declarations */ 

#ifndef __IVsLog_FWD_DEFINED__
#define __IVsLog_FWD_DEFINED__
typedef interface IVsLog IVsLog;

#endif 	/* __IVsLog_FWD_DEFINED__ */


#ifndef __IVsSqm_FWD_DEFINED__
#define __IVsSqm_FWD_DEFINED__
typedef interface IVsSqm IVsSqm;

#endif 	/* __IVsSqm_FWD_DEFINED__ */


#ifndef __IVsSqm2_FWD_DEFINED__
#define __IVsSqm2_FWD_DEFINED__
typedef interface IVsSqm2 IVsSqm2;

#endif 	/* __IVsSqm2_FWD_DEFINED__ */


#ifndef __IVsSqmOptinManager_FWD_DEFINED__
#define __IVsSqmOptinManager_FWD_DEFINED__
typedef interface IVsSqmOptinManager IVsSqmOptinManager;

#endif 	/* __IVsSqmOptinManager_FWD_DEFINED__ */


/* header files for imported files */
#include "oaidl.h"
#include "ocidl.h"

#ifdef __cplusplus
extern "C"{
#endif 


#ifndef __IVsLog_INTERFACE_DEFINED__
#define __IVsLog_INTERFACE_DEFINED__

/* interface IVsLog */
/* [object][unique][helpstring][uuid] */ 


EXTERN_C const IID IID_IVsLog;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    MIDL_INTERFACE("2508FDF0-EF80-4366-878E-C9F024B8D981")
    IVsLog : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE Enter----Error( 
            /* [in] */ GUID guid----Guid,
            /* [in] */ __RPC__in LPOLESTR bstrDescription,
            /* [in] */ __RPC__in LPOLESTR bstrHelpFile,
            /* [in] */ DWORD dwHelpContext,
            /* [in] */ HRESULT hrStatus) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE EnterVsLogEntry( 
            /* [in] */ __RPC__in LPOLESTR bstrEntry) = 0;
        
    };
    
    
#else 	/* C style interface */

    typedef struct IVsLogVtbl
    {
        BEGIN_INTERFACE
        
        HRESULT ( STDMETHODCALLTYPE *QueryInterface )( 
            __RPC__in IVsLog * This,
            /* [in] */ __RPC__in REFIID riid,
            /* [annotation][iid_is][out] */ 
            _COM_Outptr_  void **ppvObject);
        
        ULONG ( STDMETHODCALLTYPE *AddRef )( 
            __RPC__in IVsLog * This);
        
        ULONG ( STDMETHODCALLTYPE *Release )( 
            __RPC__in IVsLog * This);
        
        HRESULT ( STDMETHODCALLTYPE *Enter----Error )( 
            __RPC__in IVsLog * This,
            /* [in] */ GUID guid----Guid,
            /* [in] */ __RPC__in LPOLESTR bstrDescription,
            /* [in] */ __RPC__in LPOLESTR bstrHelpFile,
            /* [in] */ DWORD dwHelpContext,
            /* [in] */ HRESULT hrStatus);
        
        HRESULT ( STDMETHODCALLTYPE *EnterVsLogEntry )( 
            __RPC__in IVsLog * This,
            /* [in] */ __RPC__in LPOLESTR bstrEntry);
        
        END_INTERFACE
    } IVsLogVtbl;

    interface IVsLog
    {
        CONST_VTBL struct IVsLogVtbl *lpVtbl;
    };

    

#ifdef COBJMACROS


#define IVsLog_QueryInterface(This,riid,ppvObject)	\
    ( (This)->lpVtbl -> QueryInterface(This,riid,ppvObject) ) 

#define IVsLog_AddRef(This)	\
    ( (This)->lpVtbl -> AddRef(This) ) 

#define IVsLog_Release(This)	\
    ( (This)->lpVtbl -> Release(This) ) 


#define IVsLog_Enter----Error(This,guid----Guid,bstrDescription,bstrHelpFile,dwHelpContext,hrStatus)	\
    ( (This)->lpVtbl -> Enter----Error(This,guid----Guid,bstrDescription,bstrHelpFile,dwHelpContext,hrStatus) ) 

#define IVsLog_EnterVsLogEntry(This,bstrEntry)	\
    ( (This)->lpVtbl -> EnterVsLogEntry(This,bstrEntry) ) 

#endif /* COBJMACROS */


#endif 	/* C style interface */




#endif 	/* __IVsLog_INTERFACE_DEFINED__ */


/* interface __MIDL_itf_vslog_0000_0001 */
/* [local] */ 

typedef 
enum vsSqmDatapoint
    {
        Undefined	= 0,
        DATAID_SQM_ACTIVATEDOCWINDOW	= 1,
        DATAID_SQM_UICONTEXTCHANGED	= 2,
        DATAID_SQM_PERFMEMORY	= 3,
        DATAID_SQM_STARTUPOS	= 4,
        DATAID_SQM_STARTUPOSVERSION	= 5,
        DATAID_SQM_STARTUPOSBUILD	= 6,
        DATAID_SQM_STARTUPOSSERVICEPACK	= 7,
        DATAID_SQM_STARTUPAPPID	= 8,
        DATAID_SQM_STARTUPAPPBUILDTYPE	= 9,
        DATAID_SQM_STARTUPAPPVERSION	= 10,
        DATAID_SQM_STARTUPAPPBUILDNUMBER	= 11,
        DATAID_SQM_STARTUPAPPPRODUCTLOCALE	= 12,
        DATAID_SQM_STARTUPAPPSYSTEMLOCALE	= 13,
        DATAID_SQM_STARTUPAPPUSERLOCALE	= 14,
        DATAID_SQM_PERFCPUCOUNT	= 15,
        DATAID_SQM_PERFPROCFAMILY	= 16,
        DATAID_SQM_PERFPROCMODEL	= 17,
        DATAID_SQM_PERFPROCSTEPPING	= 18,
        DATAID_SQM_PERFPROCFREQUENCY	= 19,
        DATAID_SQM_EVTIDLE	= 20,
        DATAID_SQM_SHUTDOWNREASON	= 21,
        DATAID_SQM_ACTIVATETOOLWINDOW	= 22,
        DATAID_SQM_EVTDEBUG	= 23,
        DATAID_SQM_SESSIONDURATION	= 24,
        DATAID_SQM_SESSIONIDLE	= 25,
        DATAID_SQM_EVTSELECTIONCHANGED	= 26,
        DATAID_SQM_WATSONUPLOAD	= 27,
        DATAID_SQM_EVTBEFORECOMMANDEXECUTES	= 28,
        DATAID_SQM_ASSERT	= 29,
        DATAID_SQM_COMPLUSVERSION	= 30,
        DATAID_SQM_STRING	= 31,
        DATAID_SQM_VSEDITION	= 32,
        DATAID_SQM_VSADDINCOUNT	= 33,
        DATAID_SQM_DISPLAYCOUNT	= 34,
        DATAID_SQM_VSBUILDRCNUMBER	= 35,
        DATAID_SQM_USERPRIV	= 36,
        DATAID_SQM_USERTYPE	= 37,
        DATAID_SQM_VSPROFILE	= 38,
        DATAID_SQM_IEVER	= 39,
        DATAID_STRM_VB_ERROR	= 40,
        DATAID_SQM_DISPLAYRESOLUTION	= 41,
        DATAID_SQM_VSSKU	= 42,
        DATAID_SQM_VOLUMESIZE	= 43,
        DATAID_SQM_FREEDISKSPACE	= 44,
        DATAID_SQM_COLORDEPTH	= 45,
        DATAID_SQM_MDI	= 46,
        DATAID_SQM_VSPROJECTS	= 47,
        DATAID_SQM_VSCOMMANDS	= 48,
        DATAID_SQM_VSSOLUTIONS	= 49,
        DATAID_SQM_VSSCCHANGE	= 50,
        DATAID_SQM_HDSIZE	= 51,
        DATAID_SQM_VSTOOLWINS	= 52,
        DATAID_SQM_PKGLOAD	= 53,
        DATAID_STRM_VB_AUTO_OPEN	= 54,
        DATAID_STRM_VB_AUTO_APPEAR_ERROR	= 55,
        DATAID_STRM_VB_AUTO_PICK	= 56,
        DATAID_STRM_VB_AUTO_APPEAR_HOVER	= 57,
        DATAID_SQM_PKGINST	= 58,
        DATAID_SQM_NUMMACROSINST	= 59,
        DATAID_SQM_CSHARP_IDE_UNMANAGED_ERROR	= 60,
        DATAID_STRM_VB_DEBUGGER_CONTINUE	= 61,
        DATAID_STRM_VB_DEBUGGER_RUNMSGS	= 62,
        DATAID_STRM_VB_DEBUGGER_NEWRUN	= 63,
        DATAID_STRM_VB_DEBUGGER_COMPILERSTATE	= 64,
        DATAID_STRM_VB_DEBUGGER_SETBREAKLINE	= 65,
        DATAID_STRM_VB_EDITOR_INTELLISENSETABCHANGE	= 66,
        DATAID_STRM_VB_EDITOR_PROJPROPSHOW	= 67,
        DATAID_STRM_VB_EDITOR_NUMLOCALIZEDFILES	= 68,
        DATAID_STRM_VB_EDITOR_FORMRENAME	= 69,
        DATAID_STRM_VB_EXCEPTION_SHOW	= 70,
        DATAID_STRM_VB_EXCEPTION_ONLINEHELP	= 71,
        DATAID_STRM_VB_SNIPPETUPGRADE_FINISH	= 72,
        DATAID_STRM_VB_UPGRADEWIZARD_START	= 73,
        DATAID_STRM_VB_UPGRADEWIZARD_FINISH	= 74,
        DATAID_STRM_VB_SOLUTION_EMBEDDED	= 75,
        DATAID_STRM_VB_SOLUTION_STATS	= 76,
        DATAID_STRM_VB_SOLUTION_OPTIONS	= 77,
        DATAID_STRM_VB_SOLUTION_NOTIFICATION	= 78,
        DATAID_DP_VB_EDITOR_INTELLISENSETABSHOW	= 79,
        DATAID_DP_VB_SNIPPETUPGRADE_START	= 80,
        DATAID_SQM_OWNINGVSSKU	= 81,
        DATAID_SQM_OWNINGVSBUILDNUMBER	= 82,
        DATAID_SQM_OWNINGVSPROFILE	= 83,
        DATAID_DP_VB_EDITOR_INTELLISENSETABALL	= 84,
        DATAID_DP_VB_EDITOR_INTELLISENSETABCOMMON	= 85,
        DATAID_DP_VB_SOLUTION_EMBEDDEDTRUE	= 86,
        DATAID_DP_VB_SOLUTION_EMBEDDEDFALSE	= 87,
        DATAID_SQM_OWNINGVSBUILDRCNUMBER	= 88,
        DATAID_SQM_VDT_CM_PROVIDERDATASOURCE	= 89,
        DATAID_SQM_VDT_SE_NUMBERTABLESENUM	= 90,
        DATAID_DP_VDT_SE_NOCONNECTIONS	= 91,
        DATAID_SQM_VDT_SE_DRAGSOURCE	= 92,
        DATAID_SQM_NAVTOHELP	= 93,
        DATAID_SQM_VSHELPOPTEXTINT	= 94,
        DATAID_SQM_VSHELPOPTONLINE	= 95,
        DATAID_SQM_VSHELPTOPICONLINE	= 96,
        DATAID_SQM_VSHELPTOPICLOCAL	= 97,
        DATAID_SQM_VDT_COLPROP_COLPROPUSAGE	= 98,
        DATAID_V_VDT_DDIAG_CHANGESCRIPTS	= 99,
        DATAID_SQM_VDT_DDIAG_DBOCREATE	= 100,
        DATAID_SQM_VDT_DDIAG_DDIAGUSAGE	= 101,
        DATAID_SQM_VDT_DDIAG_DIAGDISCARD	= 102,
        DATAID_SQM_VDT_DDIAG_NODIAGRAMTABLE	= 103,
        DATAID_SQM_VDT_DDIAG_NONDBOCREATE	= 104,
        DATAID_SQM_VDT_DDIAG_RELATIONSHIPCREATION	= 105,
        DATAID_SQM_VDT_DDIAG_TABLEVIEWOPCHANGE	= 106,
        DATAID_SQM_VDT_TD_COLUMNPROPERTIES	= 107,
        DATAID_SQM_VDT_TD_DIALOGUSAGE	= 108,
        DATAID_SQM_VDT_TD_SCRIPTGEN	= 109,
        DATAID_SQM_VDT_TD_TDUSAGE	= 110,
        DATAID_SQM_VDT_SE_NUMBERASSEMBLIESENUM	= 111,
        DATAID_SQM_VDT_SE_NUMBERDRAGOBJECTS	= 112,
        DATAID_SQM_VDT_SE_NUMBERFUNCTIONSENUM	= 113,
        DATAID_SQM_VDT_SE_NUMBEROTHERENUM	= 114,
        DATAID_SQM_VDT_SE_NUMBERSPROCSENUM	= 115,
        DATAID_SQM_VDT_SE_NUMBERSYNONYMSENUM	= 116,
        DATAID_V_VDT_SE_NUMBERVIEWSENUM	= 117,
        DATAID_SQM_VDT_SQLCLR_USEAGE	= 118,
        DATAID_SQM_VDT_QD_UPDATEUSAGE	= 119,
        DATAID_SQM_VDT_QD_QUERYSAVED	= 120,
        DATAID_SQM_VDT_QD_SELECTUSAGE	= 121,
        DATAID_SQM_VDT_QD_SQLUSAGE	= 122,
        DATAID_SQM_VDT_QD_QUERYNOTSAVED	= 123,
        DATAID_SQM_VDT_QD_NONFROMCLAUSES	= 124,
        DATAID_SQM_VDT_QD_MAKETABLEUSAGE	= 125,
        DATAID_SQM_VDT_QD_INSERTVALUESUSAGE	= 126,
        DATAID_SQM_VDT_QD_INSERTRESULTSUSAGE	= 127,
        DATAID_SQM_VDT_QD_FROMVIEWS	= 128,
        DATAID_SQM_VDT_QD_FROMTABLES	= 129,
        DATAID_SQM_VDT_QD_FROMSUBQUERIES	= 130,
        DATAID_SQM_VDT_QD_FROMROWSET	= 131,
        DATAID_DP_VDT_QD_DIAGUSAGE	= 132,
        DATAID_SQM_VDT_QD_CRITERIAUSAGE	= 133,
        DATAID_SQM_VDT_QD_DELETEUSAGE	= 134,
        DATAID_SQM_VDT_QD_RUNQUERYUSAGE	= 135,
        DATAID_SQM_VDT_VD_VIEWSAVED	= 136,
        DATAID_SQM_VDT_VD_VIEWNOTSAVED	= 137,
        DATAID_SQM_VDT_VD_VIEWPROVIDERUSAGE	= 138,
        DATAID_SQM_VDT_QD_PROVIDERUSAGE	= 139,
        DATAID_SQM_VDT_TSQLE_QBUSAGE	= 140,
        DATAID_SQM_VDT_DBPROJ_USEOFSC	= 141,
        DATAID_SQM_VDT_DBPROJ_NOOFSQLFILES	= 142,
        DATAID_SQM_VDT_DBPROJ_NOOFDTQFILES	= 143,
        DATAID_SQM_VDT_DBPROJ_SCRIPTING	= 144,
        DATAID_SQM_VDT_DBPROJ_DBPROJUSAGE	= 145,
        DATAID_SQM_VDT_DBPROJ_PROVIDERUSAGE	= 146,
        DATAID_SQM_VDT_DBPROJ_QBUSAGE	= 147,
        DATAID_SQM_VDT_DDIAG_DIAGSAVED	= 148,
        DATAID_SQM_VDT_QD_SQLFEATUREUSAGE	= 149,
        DATAID_SQM_VDT_QD_GENERICFEATUREUSAGE	= 150,
        DATAID_SQM_VDT_SQLCLR_FAILUREERROR	= 151,
        DATAID_SQM_VDT_QD_MAXFROMCLAUSEUSAGE	= 152,
        DATAID_STRM_VB_DATA_REENTRANTWIZARD	= 153,
        DATAID_STRM_VB_DATA_GENCOMMANDS	= 154,
        DATAID_STRM_VB_DATA_CONNCONSUMPTION	= 155,
        DATAID_STRM_VB_DATA_ADDSOURCE	= 156,
        DATAID_STRM_VB_DATA_NUMTABLES	= 157,
        DATAID_STRM_VB_DATA_ADDQUERY	= 158,
        DATAID_STRM_VB_DATA_EVERETTWIZARD	= 159,
        DATAID_STRM_VB_DATA_ADDQUERYTOADAPTER	= 160,
        DATAID_STRM_VB_DATA_INPUTQUERY	= 161,
        DATAID_SQM_HASVSDEVKEY	= 162,
        DATAID_SQM_CLEARTYPE	= 163,
        DATAID_SQM_EXENAME	= 164,
        DATAID_SQM_VDT_QD_VERIFYSQL	= 165,
        DATAID_SQM_NUMADDINSINST	= 166,
        DATAID_SQM_NUMADDINSLOAD	= 167,
        DATAID_SQM_NUMADDINSLOADSUCCESS	= 168,
        DATAID_SQM_HIGHCONTRAST	= 169,
        DATAID_SQM_CSHARP_IDE_AUTOCOMPLETE_ONOFF	= 170,
        DATAID_SQM_CSHARP_IDE_COMPLETIONKEY	= 171,
        DATAID_SQM_CSHARP_IDE_COMPLETIONCHARCHANGE	= 172,
        DATAID_SQM_CSHARP_IDE_EXTERNALIASCOUNT	= 173,
        DATAID_SQM_CSHARP_IDE_FORMATSETTINGS1	= 174,
        DATAID_SQM_CSHARP_IDE_COMPILER_ERROR	= 175,
        DATAID_SQM_CSHARP_IDE_COMPILERREFACTORCOUNT	= 176,
        DATAID_SQM_CSHARP_IDE_PREVIEWCHANGES	= 177,
        DATAID_SQM_CSHARP_IDE_PREVIEWCHANGECANCEL	= 178,
        DATAID_SQM_CSHARP_ENC_CONTINUE	= 179,
        DATAID_SQM_CSHARP_ENC_APPLY	= 180,
        DATAID_SQM_CSHARP_ENC_PROJECTFILESCHANGED	= 181,
        DATAID_SQM_CSHARP_ENC_ERRORCOUNT	= 182,
        DATAID_SQM_TEXTEDITORFONTNAME	= 183,
        DATAID_SQM_VSPROJECTPOLICY	= 184,
        DATAID_SQM_CSHARP_IDE_FORMATSETTINGS2	= 185,
        DATAID_SQM_CSHARP_IDE_MANAGED_ERROR	= 186,
        DATAID_SQM_VSDPROJECTS	= 187,
        DATAID_SQM_VSTOPROJECTS	= 188,
        DATAID_STRM_VSD_CONNECTION	= 189,
        DATAID_STRM_VSD_DEPLOYMENT	= 190,
        DATAID_SQM_DEBUGGER_FUNCEVALABORT	= 191,
        DATAID_SQM_VSD_CONNECTIONATTEMPTED	= 192,
        DATAID_SQM_VSD_CONNECTIONSUCCEEDED	= 193,
        DATAID_SQM_VSD_DEPLOYFILESIZE	= 194,
        DATAID_SQM_VSD_DEPLOYNUMFILES	= 195,
        DATAID_SQM_DEBUGGER_ERRORS	= 196,
        DATAID_SQM_DEBUGGER_ENC_ERRORREASON	= 197,
        DATAID_SQM_CSHARP_IDE_COMPLETIONCHARCHA_64828_NEW	= 198,
        DATAID_SQM_LOCALHELPTOPIC	= 199,
        DATAID_SQM_VSD_DEBUGDEVICE	= 200,
        DATAID_SQM_VSD_DEBUGWASTON	= 201,
        DATAID_SQM_DEBUGCONNECTIONERROR	= 202,
        DATAID_SQM_VSEDITORSGETFOCUS	= 203,
        DATAID_SQM_VSEDITORSLOSEFOCUS	= 204,
        DATAID_SQM_TEST	= 205,
        DATAID_SQM_KEYBINDINGSSCHEMENAME	= 206,
        DATAID_STRM_VC_COMPILER_SWITCH	= 207,
        DATAID_STRM_VC_COMPILER_DIAGNOSTICS	= 208,
        DATAID_STRM_VC_IDE_PROJECTSTATISTICS	= 209,
        DATAID_STRM_VC_COMPILER_PARENTPROCESS	= 210,
        DATAID_STRM_VC_IDE_INTELLISENSE	= 211,
        DATAID_STRM_VC_IDE_RESOURCEEDITOR	= 212,
        DATAID_STRM_VC_COMPILER_TARGET	= 213,
        DATAID_STRM_VC_IDE_WIZARDS	= 214,
        DATAID_SQM_VSD_DEVICEINFO	= 215,
        DATAID_STRM_VC_COMPILER_MACRO_DEFINITION	= 216,
        DATAID_SQM_ENVFONTNAME	= 217,
        DATAID_SQM_SCREENDPI	= 218,
        DATAID_SQM_ENVFONTSIZE	= 219,
        DATAID_SQM_DELAYNOTIFICATION	= 220,
        DATAID_SQM_NUMCDDRIVES	= 221,
        DATAID_SQM_NUMDVDDRIVES	= 222,
        DATAID_SQM_VSD_CHANGEPLATFORM	= 223,
        DATAID_SQM_VSD_UPGRADEPROJECT	= 224,
        DATAID_SQM_CONNECTIONERROR	= 225,
        DATAID_SQM_CSHARP_REFACTOR_COMMANDERROR	= 226,
        DATAID_SQM_CSHARP_REFACTOR_WARNINGDIAG	= 227,
        DATAID_SQM_CSHARP_IDE_PREVIEWDIAG	= 228,
        DATAID_SQM_SCREENREADER	= 229,
        DATAID_SQM_VSCORE_TEMPLATE_SELECTION	= 230,
        DATAID_SQM_VSCORE_P2P_REFERENCES	= 231,
        DATAID_SQM_VSCORE_FILE_REFERENCES	= 232,
        DATAID_SQM_NUMBEROFFILESPERBUILDACTION	= 233,
        DATAID_SQM_VSD_DATA_GENERATEDATAFORMS	= 234,
        DATAID_SQM_VSD_DATA_SQLMOBILEINSERVEREXPLORER	= 235,
        DATAID_SQM_VSD_DATA_DRAGDROP	= 236,
        DATAID_SQM_VSD_DATA_DATASOURCEGENERATION	= 237,
        DATAID_SQM_VSD_DATA_MANAGEMENTUI	= 238,
        DATAID_SQM_VENUS_WEBPROJECTLANGTYPE	= 239,
        DATAID_STRM_VB_WEBSVC_HOSTTYPE	= 240,
        DATAID_DP_JLCA_MIGRATION_START	= 241,
        DATAID_DP_JLCA_MIGRATION_SUCCESS	= 242,
        DATAID_DP_JLCA_MIGRATION_CANCEL	= 243,
        DATAID_DP_JLCA_MIGRATION_FAILURE	= 244,
        DATAID_DP_VB_EDITOR_INTELLISENSETABSHOWALL	= 245,
        DATAID_SQM_FILESYSTEMTYPE	= 246,
        DATAID_STRM_VB_UPGRADEWIZARD_ISSUES	= 247,
        DATAID_STRM_VB_UPGRADEWIZARD_COMLIBRARIES	= 248,
        DATAID_SQM_SCCPROVIDERFORPROJECT	= 249,
        DATAID_SQM_SOLNEXPLORER_PRJUSESSHOWALL	= 250,
        DATAID_STRM_VB_DATA_ADDLOCALDATACONNECTION	= 251,
        DATAID_STRM_VB_EDITOR_SNIPPETINSERT	= 252,
        DATAID_STRM_VB_EDITOR_UNDOINSERTSNIPPET	= 253,
        DATAID_STRM_VB_EDITOR_SNIPPETNEWOBJECT	= 254,
        DATAID_SQM_VSNUMEDITORMARKERS	= 255,
        DATAID_SQM_VSD_DE_RAMSIZE	= 256,
        DATAID_SQM_VSD_DE_ROMSIZE	= 257,
        DATAID_SQM_VSD_DE_HOSTKEY	= 258,
        DATAID_SQM_VSD_DE_FLASHFILE	= 259,
        DATAID_SQM_VSD_DE_CMNDXTRA	= 260,
        DATAID_SQM_VSD_DE_FUNCKEY	= 261,
        DATAID_SQM_VSD_DE_CONFIG	= 262,
        DATAID_SQM_VSD_DE_SP1	= 263,
        DATAID_SQM_VSD_DE_SP2	= 264,
        DATAID_SQM_VSD_DE_SP3	= 265,
        DATAID_SQM_VSD_DE_RECORDAUDIO	= 266,
        DATAID_SQM_VSD_DE_PLAYAUDIO	= 267,
        DATAID_SQM_VSD_DE_EXDI	= 268,
        DATAID_SQM_VSD_DE_TABLETINK	= 269,
        DATAID_SQM_VSD_DE_LAUNCHTYPE	= 270,
        DATAID_SQM_VSD_DE_NE2000	= 271,
        DATAID_SQM_VSD_DE_CS8900	= 272,
        DATAID_SQM_VSD_DE_HARDRESET	= 273,
        DATAID_SQM_VSD_DE_SOFTRESET	= 274,
        DATAID_SQM_VSD_DE_SKINCHANGE	= 275,
        DATAID_SQM_VSD_DE_MMTIMER	= 276,
        DATAID_SQM_VSD_DE_COMPORTS	= 277,
        DATAID_SQM_VSD_DE_TERMINATE	= 278,
        DATAID_SQM_VSD_DE_INTLOST	= 279,
        DATAID_SQM_VSD_DE_VPCPOWERATTEMPT	= 280,
        DATAID_SQM_VSD_DE_VPCPOWERFAILED	= 281,
        DATAID_SQM_VSD_DE_DMASENT	= 282,
        DATAID_SQM_VSD_DE_DMARCVD	= 283,
        DATAID_SQM_VSD_DE_DMALOST	= 284,
        DATAID_SQM_VSD_DEM_ACTIONFAILED	= 285,
        DATAID_SQM_VSD_DEM_ACTIONLAUNCHED	= 286,
        DATAID_SQM_VSD_DEM_LAUNCHED	= 287,
        DATAID_SQM_VSD_DEM_FAILED	= 288,
        DATAID_SQM_VSD_DEM_NONCORECONEMU	= 289,
        DATAID_SQM_VSD_DEM_RUNNINGEMU	= 290,
        DATAID_SQM_VSD_DEM_CORECON	= 291,
        DATAID_SQM_VSDDE_STARTUPOS	= 292,
        DATAID_SQM_VSDDE_STARTUPOSBUILD	= 293,
        DATAID_SQM_VSDDE_OSLOCALE	= 294,
        DATAID_SQM_VSDDE_OSSERVICEPACK	= 295,
        DATAID_SQM_VSDDE_OSVERSION	= 296,
        DATAID_SQM_VSD_DE_VERSION	= 297,
        DATAID_SQM_VSD_DE_STARTUPAPPID	= 298,
        DATAID_SQM_VSD_DE_BUILDRCNUMBER	= 299,
        DATAID_SQM_VSD_DE_BUILDNUM	= 300,
        DATAID_SQM_VSD_DE_PERFCPUCOUNT	= 301,
        DATAID_SQM_VSD_DE_PERFMEMORY	= 302,
        DATAID_SQM_VSD_DE_PERFPROCFAMILY	= 303,
        DATAID_SQM_VSD_DE_PERFPROCFREQUENCY	= 304,
        DATAID_SQM_VSD_DE_PERFPROCMODEL	= 305,
        DATAID_SQM_VSD_DEM_ACTION	= 306,
        DATAID_SQM_VSD_DE_SERIALPORT	= 307,
        DATAID_SQM_LOCALVER_IVSSOLUTIONEVENTS	= 308,
        DATAID_SQM_LOCALVER_IVSUPDATESOLUTIONEVENTS	= 309,
        DATAID_SQM_LOCALVER_IVSRUNNINGDOCUMENTTABLEEVENTS	= 310,
        DATAID_SQM_LOCALVER_IVSTRACKPROJECTDOCUMENTEVENTS2	= 311,
        DATAID_SQM_LOCALVER_STOREOPERATIONS	= 312,
        DATAID_SQM_VSD_DE_USERTYPE	= 313,
        DATAID_SQM_VSD_DE_STARTUPAPPPRODUCTLOCALE	= 314,
        DATAID_SQM_VSD_DE_APPBUILDTYPE	= 315,
        DATAID_SQM_VSD_DE_STARTUPAPPVERSION	= 316,
        DATAID_SQM_VSD_DE_FOLDERSHARE	= 317,
        DATAID_SQM_VSD_DE_RTCADJUST	= 318,
        DATAID_SQM_VSD_DE_LAUNCHFAILED	= 319,
        DATAID_STRM_TSDATA_COMPAREENCRYPTEDPROCS	= 320,
        DATAID_STRM_TSDATA_EDITORRESULTSIZE	= 321,
        DATAID_STRM_TSDATA_REFACTORINGPREVIEW	= 322,
        DATAID_STRM_TSDATA_COMPAREDATAENCRYPTEDCOLUMN	= 323,
        DATAID_STRM_TSDATA_SCHEMACOMPAREERROR	= 324,
        DATAID_STRM_TSDATA_SCHEMACOMPAREUPDATE	= 325,
        DATAID_STRM_TSDATA_TESTGEN	= 326,
        DATAID_STRM_TSDATA_COMPAREENCRYPTEDPROC	= 327,
        DATAID_STRM_TSDATA_OBJECTTYPE	= 328,
        DATAID_STRM_TSDATA_GENERATETEST	= 329,
        DATAID_SQM_CODEANALYSIS_USAGE_ENABLECA	= 330,
        DATAID_SQM_CODEANALYSIS_USAGE_NUMBEROFCABUILDS	= 331,
        DATAID_SQM_CODEANALYSIS_USAGE_NUMBEROFONETIMEBUILDS	= 332,
        DATAID_SQM_CODEANALYSIS_ANALYSIS_NUMBEROFVIOLATIONSINERRORLIST	= 333,
        DATAID_SQM_CODEANALYSIS_ANALYSIS_RULESFIRED	= 334,
        DATAID_SQM_CODEANALYSIS_ANALYSIS_RULESUPPRESSION	= 335,
        DATAID_SQM_CODEANALYSIS_USAGE_NUMBEROFBUILDS	= 336,
        DATAID_SQM_CODEANALYSIS_USAGE_RULESELECTION	= 337,
        DATAID_SQM_CODEANALYSIS_USAGE_RULESEVERITY	= 338,
        DATAID_STRM_AVRFVS_MENU	= 339,
        DATAID_STRM_AVRFVS_SETTINGS	= 340,
        DATAID_STRM_AVRFVS_STOP	= 341,
        DATAID_STRM_AVRFVS_STOP_DIALOG_BUTTON	= 342,
        DATAID_SQM_SETUPFAIL	= 343,
        DATAID_SQM_SETUPSTART	= 344,
        DATAID_SQM_SETUPSUCCEED	= 345,
        DATAID_SQM_STRM_VB_EDITOR_STATEMENTCOMPLETIONCOMMIT	= 346,
        DATAID_SQM_DEXPLORESTATE	= 347,
        DATAID_SQM_DOCUMENTATION_WIN32STATE	= 348,
        DATAID_SQM_DOCUMENTATION_FXSTATE	= 349,
        DATAID_SQM_SAMPLES_WIN32STATE	= 350,
        DATAID_SQM_SAMPLES_WINFX_ZIPSTATE	= 351,
        DATAID_SQM_SAMPLES_WINFX_DOCSSTATE	= 352,
        DATAID_SQM_DEVTOOLS_VISTAHEADERSLIBSSTATE	= 353,
        DATAID_SQM_DEVTOOLS_HEADERFILESSTATE	= 354,
        DATAID_SQM_DEVTOOLS_X86LIBSSTATE	= 355,
        DATAID_SQM_DEVTOOLS_X64LIBSSTATE	= 356,
        DATAID_SQM_DEVTOOLS_IA64LIBSSTATE	= 357,
        DATAID_SQM_DEVTOOLS_VCCOMPILERSSTATE	= 358,
        DATAID_SQM_DEVTOOLS_X86COMPILERSSTATE	= 359,
        DATAID_SQM_DEVTOOLS_X64COMPILERSSTATE	= 360,
        DATAID_SQM_DEVTOOLS_IA64COMPILERSSTATE	= 361,
        DATAID_SQM_DEVTOOLS_FXCOPSTATE	= 362,
        DATAID_SQM__DEVTOOLS_WINDBGSTATE	= 363,
        DATAID_SQM_DEVTOOLS_WIN32DESKTOPTOOLSSTATE	= 364,
        DATAID_SQM_DEVTOOLS_FXDESKTOPTOOLSSTATE	= 365,
        DATAID_SQM_DEVTOOLS_CFSTATE	= 366,
        DATAID_SQM_DP_VB_DATA_TYPEDDATASET_ENABLETABLEADAPTERMANAGER	= 367,
        DATAID_SQM_DP_VB_DATA_TYPEDDATASET_UPDATEORDER	= 368,
        DATAID_SQM_DP_VB_DATA_TYPEDDATASET_BACKUPBEFOREUPDATE	= 369,
        DATAID_SQM_STRM_VB_DATA_TYPEDDATASET_BACKUPBEFOREUPDATE	= 370,
        DATAID_SQM_STRM_VB_DATA_TYPEDDATASET_ENABLETABLEADAPTERMANAGER	= 371,
        DATAID_SQM_STRM_VB_DATA_TYPEDDATASET_UPDATEORDER	= 372,
        DATAID_SQM_DESIGN_TIME_ERROR	= 373,
        DATAID_SQM_STRM_VB_DATA_NTIER	= 374,
        DATAID_SQM_DP_VB_FG_WAIT	= 375,
        DATAID_SQM_DP_VB_FG_WAIT_CANCEL	= 376,
        DATAID_DP_VSD_DEMAPI_LAUNCH	= 377,
        DATAID_DP_VSD_DEMAPI_DECFG_EMU	= 378,
        DATAID_DP_VSD_DECFG_EMU_CONNECT	= 379,
        DATAID_SQM_PROFILER_NUM_LAUNCHES	= 380,
        DATAID_SQM_PROFILER_NUM_SAMPLING_LAUNCHES	= 381,
        DATAID_SQM_PROFILER_NUM_INSTR_LAUNCHES	= 382,
        DATAID_SQM_PROFILER_NUM_ASPNET_LAUNCHES	= 383,
        DATAID_SQM_PROFILER_NUM_WCF_LAUNCHES	= 384,
        DATAID_SQM_PROFILER_NUM_VSP_REPORTS	= 385,
        DATAID_SQM_PROFILER_NUM_EXECUTE_FILTER	= 386,
        DATAID_SQM_PROFILER_NUM_CPP_LAUNCHES	= 387,
        DATAID_SQM_PROFILER_NUM_VB_LAUNCHES	= 388,
        DATAID_SQM_PROFILER_NUM_CS_LAUNCHES	= 389,
        DATAID_STRM_VC_IDE_DIALOGEDITORCONTROLS	= 390,
        DATAID_SQM_PLATFORM	= 391,
        DATAID_SQM_CFVERSION	= 392,
        DATAID_SQM_PROJECTTYPE	= 393,
        DATAID_SQM_VSD_LANGUAGE	= 394,
        DATAID_SQM_CFVERSION1	= 395,
        DATAID_SQM_VSD_LANGUAGE1	= 396,
        DATAID_SQM_PLATFORM1	= 397,
        DATAID_SQM_PROJECTTYPE1	= 398,
        DATAID_SQM_VSD_DEMAPI_DECFG_EMU	= 399,
        DATAID_STRM_VC_IDE_DIALOGEDITORCTRLS	= 400,
        DATAID_SQM_VSD_PROJECT	= 401,
        DATAID_STRM_VSD_PROJECTCREATE	= 402,
        DATAID_SQM_DP_VB_XMLTOSCHEMAWIZARD_USEWIZARD	= 403,
        DATAID_SQM_DP_VB_XMLTOSCHEMAWIZARD_FROMFILE	= 404,
        DATAID_SQM_DP_VB_XMLTOSCHEMAWIZARD_FROMWEB	= 405,
        DATAID_SQM_DP_VB_XMLTOSCHEMAWIZARD_FROMXML	= 406,
        DATAID_SQM_STRM_VB_XMLTOSCHEMAWIZARD_EXCEPTION	= 407,
        DATAID_SQM_XMLEDITOR_FILESIZE	= 408,
        DATAID_SQM_XMLEDITOR_FILEEXTENSION1	= 409,
        DATAID_SQM_XMLEDITOR_SCHEMADOWNLOAD	= 410,
        DATAID_SQM_XMLEDITOR_GENERATEDSCHEMAEXTENTION1	= 411,
        DATAID_SQM_XMLEDITOR_ERRORLISTUSED	= 412,
        DATAID_SQM_XMLEDITOR_SCHEMADIALOGLAUNCH	= 413,
        DATAID_SQM_XMLEDITOR_SCHEMADIALOGCHANGE	= 414,
        DATAID_SQM_XMLEDITOR_SCHEMADIALOGITEMS	= 415,
        DATAID_SQM_XMLEDITOR_CREATESCHEMA	= 416,
        DATAID_SQM_XMLEDITOR_SCHEMACACHE	= 417,
        DATAID_SQM_XMLEDITOR_STATICSNIPPETS	= 418,
        DATAID_SQM_CSHARP_IDE_LIVEERRORS_ONOFF	= 419,
        DATAID_SQM_XMLEDITOR_NAMESPACE	= 420,
        DATAID_SQM_XMLEDITOR_ERRORLIST	= 421,
        DATAID_SQM_XMLEDITOR_SNIPPETSGENERATED	= 422,
        DATAID_DATAID_SP_TIMETOFIRSTWINDOW	= 423,
        DATAID_DATAID_SP_SYSTEMFREEDISKSPACE	= 424,
        DATAID_DATAID_SP_INSTALLITEM	= 425,
        DATAID_DATAID_SP_ISINTERNAL	= 426,
        DATAID_DATAID_SP_ISADMIN	= 427,
        DATAID_DATAID_SP_ISRETAILBUILD	= 428,
        DATAID_DATAID_SP_DISPLAYLCID	= 429,
        DATAID_DATAID_SP_DOWNLOADSIZE	= 430,
        DATAID_DATAID_SP_DOWNLOADTIME	= 431,
        DATAID_DATAID_SP_DOWNLOADITEM	= 432,
        DATAID_DATAID_SP_DOWNLOADRATE	= 433,
        DATAID_DATAID_SP_INSTALLTIME	= 434,
        DATAID_DATAID_SP_PROCESSBLOCKINGINSTALL	= 435,
        DATAID_DATAID_SP_SERVICEBLOCKINGINSTALL	= 436,
        DATAID_DATAID_SP_OPERATIONREQUESTED	= 437,
        DATAID_DATAID_SP_OPERATIONUI	= 438,
        DATAID_DATAID_SP_PACKAGENAME	= 439,
        DATAID_DATAID_SP_APPLICATIONVERSION	= 440,
        DATAID_DATAID_SP_APPLICABLESKU	= 441,
        DATAID_DATAID_SP_CURRENTSTATE	= 442,
        DATAID_DATAID_SP_RETURNCODE	= 443,
        DATAID_DATAID_SP_MSIMESSAGE	= 444,
        DATAID_DATAID_SP_NUMBEROFREFRESH	= 445,
        DATAID_DATAID_SP_REPORTMODE	= 446,
        DATAID_DATAID_SP_RETURNCODE2	= 447,
        DATAID_DATAID_SP_MSIMESSAGE2	= 448,
        DATAID_DATAID_SP_NUMBEROFREFRESH2	= 449,
        DATAID_DATAID_SP_DISPLAYLCID2	= 450,
        DATAID_DATAID_SP_DOWNLOADITEM2	= 451,
        DATAID_DATAID_SP_INSTALLITEM2	= 452,
        DATAID_DATAID_SP_OSFULLVERSION	= 453,
        DATAID_DATAID_SP_APPLICABLEIFTIME	= 454,
        DATAID_DATAID_SP_SYSTEMREQUIREMENTCHECKTIME	= 455,
        DATAID_SQM_VBTHROWVIADEVGUARD	= 456,
        DATAID_DATAID_SP_PACKAGEVERSION	= 457,
        DATAID_SQM_HISTORICAL_USAGE	= 458,
        DATAID_SQM_HISTORIC_WINDOW_DEBUG_SESSION	= 459,
        DATAID_SQM_LIVE_DEBUGGER_USAGE	= 460,
        DATAID_DATAID_SP_CURRENTITEM	= 461,
        DATAID_DATAID_SP_ERRORPHASE	= 462,
        DATAID_SQM_VSTT_CAMANO_SEARCH_COUNT	= 463,
        DATAID_SQM_TFS_VC_COMMANDSOURCE	= 464,
        DATAID_SQM_TFS_CLIENT_VERSION	= 465,
        DATAID_SQM_TFS_VC_COMMANDRESULT	= 466,
        DATAID_SQM_XMLEDITOR_FILEEXTENSION2	= 467,
        DATAID_SQM_XMLEDITOR_FILEEXTENSION3	= 468,
        DATAID_SQM_XMLEDITOR_GENERATEDSCHEMAEXTENTION2	= 469,
        DATAID_SQM_XMLEDITOR_GENERATEDSCHEMAEXTENTION3	= 470,
        DATAID_SQM_CSHARP_IDE_REFACTORVERIFY_ONOFF	= 471,
        DATAID_SQM_PKGLOAD_PKGINFO	= 472,
        DATAID_SQM_PKGLOAD_EXTERNAL_PKG_DEPRECATED	= 473,
        DATAID_SQM_PKGINST_EXTERNAL_PKG_DEPRECATED	= 474,
        DATAID_STRM_VSTT_CU_PROJECTS	= 475,
        DATAID_STRM_VSTT_PROJECTCREATE	= 476,
        DATAID_DP_VSTT_RNP_PLUGINS	= 477,
        DATAID_DP_VSTT_RNP_AGG	= 478,
        DATAID_STRM_VSTT_RNP_SESSIONINFO	= 479,
        DATAID_DP_VSTT_IEVER	= 480,
        DATAID_DP_VSTT_OSVERSION	= 481,
        DATAID_DP_VSTT_VSVERSION	= 482,
        DATAID_DP_VSTT_OSLOCALE	= 483,
        DATAID_DP_VSTT_VSLOCALE	= 484,
        DATAID_DP_VSTT_VSSKU	= 485,
        DATAID_DP_VSTT_PERFMEMORY	= 486,
        DATAID_DP_VSTT_OSARCH	= 487,
        DATAID_DP_VSTT_CPUCOUNT	= 488,
        DATAID_STRM_VSTT_MTR_TCLOADED	= 489,
        DATAID_DP_VSTT_DISPLAYRESOLUTION	= 490,
        DATAID_DP_VSTT_VSBUILDNUMBER	= 491,
        DATAID_SQM_HISTORIC_LOG_EXPANDO	= 492,
        DATAID_DP_SETUP_OS	= 493,
        DATAID_DP_SETUP_CHAININGPACKAGE	= 494,
        DATAID_DP_SETUP_OSPRERELEASE	= 495,
        DATAID_DP_SETUP_CURRENTFLAGS	= 496,
        DATAID_DP_SETUP_MPC	= 497,
        DATAID_DP_SETUP_ITEMSTREAM	= 498,
        DATAID_DP_SETUP_BLOCKERSTREAM	= 499,
        DATAID_DP_SETUP_REBOOTCOUNT	= 500,
        DATAID_DP_SETUP_RESULTDETAIL	= 501,
        DATAID_SQM_HISTORIC_LOG_OPEN	= 502,
        DATAID_SQM_HISTORIC_NAV_USAGE	= 503,
        DATAID_SQM_HISTORIC_OPTIONS	= 504,
        DATAID_DP_HISTORIC_NP_DISABLED	= 505,
        DATAID_SQM_HISTORIC_FLAT_LIST_POPLUATE	= 506,
        DATAID_LAB_MTR_ON_VIRTUAL_ENV	= 507,
        DATAID_LAB_MTR_CHECKPOINT_COUNT	= 508,
        DATAID_STRM_LAB_LE_CONFIG	= 509,
        DATAID_STRM_LAB_TWO_TFS	= 510,
        DATAID_STRM_LAB_LE_CONNECT_STATUS	= 511,
        DATAID_TEAMARCH_MODEL_USAGE	= 512,
        DATAID_LAB_CHECKPOINT_COUNT	= 513,
        DATAID_DP_SETUP_ITEMSTREAM2	= 514,
        DATAID_DP_SETUP_RESULTCODE	= 515,
        DATAID_DP_SETUP_PID_MPC	= 516,
        DATAID_DP_SETUP_CURRENTFLAGS2	= 517,
        DATAID_CPUCOUNT	= 518,
        DATAID_TFSAO_TOTALWARNINGS	= 519,
        DATAID_DEPLOYMENTINFO	= 520,
        DATAID_PHYSICALCPUCOUNT	= 521,
        DATAID_CPULOGICALCOUNT	= 522,
        DATAID_PROCESSORCLOCKSPEED	= 523,
        DATAID_PROCESSORFAMILY	= 524,
        DATAID_PROCESSORDATAWIDTH	= 525,
        DATAID_PHYSICALMEMORY	= 526,
        DATAID_CONFIGRESULTSET	= 527,
        DATAID_DP_SETUP_PROFILEFEATUREMAP	= 528,
        DATAID_DP_SETUP_CUSTOMIZE	= 529,
        DATAID_DP_SETUP_CANCELPAGE	= 530,
        DATAID_TFSAO_SETUPOPTIONS	= 531,
        DATAID_TFSAO_CONFIGURATIONCOMMAND	= 532,
        DATAID_SQM_EXTENSIONMANAGEROPENED	= 533,
        DATAID_SQM_EXTENSIONMANAGEDACTION_DEPRICATED2	= 534,
        DATAID_SQM_EXTENSIONUPDATED_DEPRICATED2	= 535,
        DATAID_SQM_VSDF_USERNAME	= 536,
        DATAID_SQM_VSDF_COMPUTERNAME	= 537,
        DATAID_SQM_VSDF_DOMAIN	= 538,
        DATAID_SQM_VSDF_BRANCH	= 539,
        DATAID_DP_VSDF_EDITORBUFFERPATH	= 540,
        DATAID_SQM_PKGLOAD_EXTERNAL_PKG	= 541,
        DATAID_SQM_PKGINST_EXTERNAL_PKG	= 542,
        DATAID_STRM_VSTT_MTR_TCLOADED2	= 543,
        DATAID_STRM_PCP_TASKS	= 544,
        DATAID_STRM_PCP_STACKS	= 545,
        DATAID_SQM_HISTORIC_OPTION_DEBUG	= 546,
        DATAID_SQM_HISTORIC_NP_STATE	= 547,
        DATAID_PROCCLOCKSPEED	= 548,
        DATAID_PHYSICALNUMBERCPU	= 549,
        DATAID_PROCFAMILY	= 550,
        DATAID_PROCDATAWIDTH	= 551,
        DATAID_RAM	= 552,
        DATAID_FULLCONFIGRESULTSET	= 553,
        DATAID_STRM_PCP_ERRORS	= 554,
        DATAID_DP_SETUP_FLAGS	= 555,
        DATAID_STRM_BIZAPPSSHAREPOINTPROJECTS	= 556,
        DATAID_STRM_BIZAPPSSHAREPOINTITEMS	= 557,
        DATAID_SQM_EXTENSIONMANAGERTOTALINSTALLEDEXTENSIONS	= 558,
        DATAID_DP_SETUP_PID_EDITION	= 559,
        DATAID_DP_SETUP_PID_ORIGEDITION	= 560,
        DATAID_DP_SETUP_PID_RANGE	= 561,
        DATAID_DP_SETUP_PID_ORIGRANGE	= 562,
        DATAID_DP_SETP_PID_INSTALLEDSKUS	= 563,
        DATAID_DP_ISDOMAINMEMBER	= 564,
        DATAID_HLP3_HELPOPTIONS	= 565,
        DATAID_SQM_SESSIONFRAGMENT_INFO	= 566,
        DATAID_INTERNAL_EXTERNAL_DATA	= 567,
        DATAID_HELP3_HELPOPTIONS	= 568,
        DATAID_DP_SETUP_PACKAGETYPE	= 569,
        DATAID_DP_SETUP_PATCHSTREAM	= 570,
        DATAID_DP_SETUP_PATCHTYPE	= 571,
        DATAID_DP_SETUP_BUILDTYPE	= 572,
        DATAID_DP_SETUP_BUILDBRANCH	= 573,
        DATAID_SQM_VSTT_CAMANO_ACTIVITY_LAUNCH_STATS	= 574,
        DATAID_STRM_VSTT_CODEDUITESTBUILDERUSAGE	= 575,
        DATAID_STRM_LAB_LERIG_STATUS	= 576,
        DATAID_WINETR_EE_SLN_GEN_EVENT	= 577,
        DATAID_WINETR_IDE_DEPLOY_EVENT	= 578,
        DATAID_WINETR_SDINT_SRCCTRL_ENABLED	= 579,
        DATAID_WINETR_SDINT_SHOWDIFFS	= 580,
        DATAID_WINETR_EE_OPENED_TYPE	= 581,
        DATAID_WINETR_BUILD_EVENT	= 582,
        DATAID_WINETR_SDINT_CHECKIN	= 583,
        DATAID_WINETR_SDINT_SHOWHIST	= 584,
        DATAID_WINETR_KD_DEBUG	= 585,
        DATAID_WINETR_EE_SLN_GEN_ERROR	= 586,
        DATAID_WINETR_SA_VIEWER_ICON_LAUNCH	= 587,
        DATAID_WINETR_SA_VIEWER_ANALYSIS_EVENT	= 588,
        DATAID_WINETR_SA_VIEWER_SELECT_DEFECT_EVENT	= 589,
        DATAID_WINETR_SA_VIEWER_SELECT_MOREINFO	= 590,
        DATAID_STRM_LAB_LS_CONFIG_EC	= 591,
        DATAID_STRM_LAB_LS_TEST_EC	= 592,
        DATAID_STRM_LAB_LS_BUILD_EC	= 593,
        DATAID_STRM_LAB_LS_FENCE_EC	= 594,
        DATAID_STRM_VSTT_MTR_S2LOADED	= 595,
        DATAID_DP_SETUP_MSIVERSION	= 596,
        DATAID_HELP3_ONLINEQUERY	= 597,
        DATAID_HELP3_OFFLINEQUERY	= 598,
        DATAID_DP_SETUP_SOURCETYPE	= 599,
        DATAID_STRM_VSTT_CAMANO_STREAMING_STATS	= 600,
        DATAID_HELP3_HLMLAUNCH	= 601,
        DATAID_HELP3_HLMACTIONS	= 602,
        DATAID_SQM_DP_ACTIVATEDATASET_DEV10	= 603,
        DATAID_SQM_STRM_CLASSDESIGNER_CLOSED_DEV10	= 604,
        DATAID_SQM_DP_CONTROLBROWSER_DEV10	= 605,
        DATAID_SQM_STRM_SYNCDESIGNER_DEV10	= 606,
        DATAID_SQM_STRM_DRAGDROP_DEV10	= 607,
        DATAID_SQM_STRM_DSWIN_DEV10	= 608,
        DATAID_SQM_STRM_VBPOWERPACKS_DEV10	= 609,
        DATAID_SQM_DP_ADONETCOMPONENT_DEV10	= 610,
        DATAID_SQM_DP_PREVIEWDATA_DEV10	= 611,
        DATAID_SQM_DP_ADDNEWDATASET_DEV10	= 612,
        DATAID_SQM_STRM_DATASOURCEWIZARD_DEV10	= 613,
        DATAID_STRM_DP_PROVIDERDATASOURCE_DEV10	= 614,
        DATAID_SQM_DP_DSWIN_REFRESHFREQUENCY_DEV10	= 615,
        DATAID_DP_SETUP_REBOOTPENDING	= 616,
        DATAID_SQM_VSTT_CAMANO_ACTION_PERFORM_STATS	= 617,
        DATAID_STRM_VSDB_PERMISSIONMAINTAINED	= 618,
        DATAID_STRM_VSDB_PROJECT_SWITCH	= 619,
        DATAID_STRM_HISTORIC_ACCESS_CALLTREE_VIEW	= 620,
        DATAID_STRM_HISTORIC_SEARCH_RESULTS	= 621,
        DATAID_STRM_HISTORIC_SEARCH_RESULTS_NAV	= 622,
        DATAID_STREAM_HISTORIC_SEARCH_CONTROL_TYPE	= 623,
        DATAID_STRM_HISTORIC_NP_DISABLED	= 624,
        DATAID_STRM_VSDB_PERFORMANCE	= 625,
        DATAID_STRM_VSDB_EXTENSIBILITY	= 626,
        DATAID_STRM_VSDB_ADD_REFERENCE	= 627,
        DATAID_STRM_VSDB_FEATURES_EXERCISED	= 628,
        DATAID_SQM_DEBUGGER_STEP	= 629,
        DATAID_STRM_BIZAPPSSHAREPOINTITEMTYPE	= 630,
        DATAID_PROFILER_REPORT_STREAM	= 631,
        DATAID_NUM_CODE_PIVOT_VIEW	= 632,
        DATAID_NUM_TEST_PIVOT_VIEW	= 633,
        DATAID_NUM_CALLING_PIVOT_VIEW	= 634,
        DATAID_NUM_RUN_CLICKS_CODE_PIVOT	= 635,
        DATAID_NUM_RUN_CLICKS_TEST_PIVOT	= 636,
        DATAID_NUM_RUN_CLICKS_CALLING_PIVOT	= 637,
        DATAID_NUM_BUILDS	= 638,
        DATAID_TIA_STREAM	= 639,
        DATAID_STRM_VSDB_SQLERROR	= 640,
        DATAID_SQM_PROFILER_NUM_HPC_LAUNCHES	= 641,
        DATAID_DP_SETUP_CURRENTITEMSTEP	= 642,
        DATAID_SQM_EXTENSIONUPDATED	= 643,
        DATAID_SQM_EXTENSIONMANAGEDACTION	= 644,
        DATAID_SQM_OSARCH	= 645,
        DATAID_SQM_PROCESSOR_DATAWIDTH	= 646,
        DATAID_SQM_VIRTUALMACHINE_INFO	= 647,
        DATAID_STRM_ENV_TYPE	= 648,
        DATAID_SQM_DEBUGGER_SESSION_PARAMS	= 649,
        DATAID_SQM_RENDERCAPABILITYTIER	= 650,
        DATAID_INSTALLSHIELDCREATED	= 651,
        DATAID_PROFILER_REPORT_STREAM_1	= 652,
        DATAID_WINIDE_PKGING_EVENT1	= 653,
        DATAID_HELP3_OSVERSION	= 654,
        DATAID_HELP3_OSSERVICEPACK	= 655,
        DATAID_HELP3_HLMVERSION	= 656,
        DATAID_HELP3_HLAVERSION	= 657,
        DATAID_MACHINEID	= 658,
        DATAID_NUM_RUN_ALL_IMPACTED_TESTS	= 659,
        DATAID_NUM_RUN_SELECTED_IMPACTED_TESTS	= 660,
        DATAID_NUM_DEBUG_ALL_IMPACTED_TESTS	= 661,
        DATAID_NUM_DEBUG_SELECTED_IMPACTED_TESTS	= 662,
        DATAID_NUM_RUN_CALLING_TESTS	= 663,
        DATAID_NUM_BUILDS_WITH_CODE_CHANGES	= 664,
        DATAID_SQM_LOCALVER_CMDPROJECTSYNCHTOCHECKPOINT	= 665,
        DATAID_SQM_LOCALVER_CMDPROJECTCREATECHECKPOINT	= 666,
        DATAID_SQM_ISREMOTEDESKTOP	= 667,
        DATAID_SQM_VIRTUALMEMORYUSAGE	= 668,
        DATAID_TIA_STREAM_1	= 669,
        DATAID_STRM_EXTENSIONMANAGERACTIONRAW	= 670,
        DATAID_SQM_EXTENSIONUPDATEDRAW	= 671,
        DATAID_STRM_TOOLBOXCONTROLUSED	= 672,
        DATAID_SQM_VSSTARTUPOPTION	= 673,
        DATAID_STRM_CMDHISTORY	= 674,
        DATAID_DATAID_SQM_DEBUGGER_SESSION_PARAMS_2	= 675,
        DATAID_SQM_VIRTUALMACHINETYPE	= 676,
        DATAID_SQM_VIRTUALMACHINEVERSION	= 677,
        DATAID_SQM_VIRTUALMACHINEHOST	= 678,
        DATAID_SQM_VIRTMEM_ATTHECLIFF	= 679,
        DATAID_SQM_VIRTMEM_LARGESTFREEBLOCK	= 680,
        DATAID_SQM_VIRTMEM_TOTALFREEMEMORY	= 681,
        DATAID_SQM_VIRTMEM_TOTALCOMMITTEDMEMORY	= 682,
        DATAID_SQM_VIRTMEM_TOTALRESERVEDMEMORY	= 683,
        DATAID_SQM_VIRTMEM_TOTALIMAGEMEMORY	= 684,
        DATAID_SQM_VIRTMEM_TOTALMAPPEDMEMORY	= 685,
        DATAID_SQM_VIRTMEM_TOTALPRIVATEMEMORY	= 686,
        DATAID_SQM_VISUALEFFECTS_AUTODETECT	= 687,
        DATAID_SQM_VISUALEFFECTS_USEHARDWAREACCELERATION	= 688,
        DATAID_SQM_WPF_HARDWAREACCELERATIONOPTION	= 689,
        DATAID_SQM_WPF_MAXMULTISAMPLEVALUE	= 690,
        DATAID_SQM_WPF_REQUIREDVIDEODRIVERDATE	= 691,
        DATAID_SQM_WPF_USEREFERENCERASTERIZER	= 692,
        DATAID_SQM_VIDEOINFO_VIDEOCARD	= 693,
        DATAID_SQM_VIDEOINFO_HARDWAREID	= 694,
        DATAID_SQM_VIDEOINFO_DRIVERDATE	= 695,
        DATAID_SQM_VIDEOINFO_DRIVERVERSION	= 696,
        DATAID_SQM_VIDEOINFO_ADAPTERCOUNT	= 697,
        DATAID_SQM_VIDEOINFO_ADAPTER	= 698,
        DATAID_SQM_VIDEOINFO_MEMORYSIZE	= 699,
        DATAID_SQM_STRM_DISPLAYDEVICEINFO	= 700,
        DATAID_SQM_DP_DISPLAYDEVICESCOUNT	= 701,
        DATAID_SQM_VIDEOINFO_ADAPTER_COUNT	= 702,
        DATAID_STRM_LABSVC_GENERALUSAGE	= 703,
        DATAID_DP_LABSVC_VSBUILDNUMBER	= 704,
        DATAID_DP_LABSVC_INTERNALEXTERNAL	= 705,
        DATAID_WINETR_EE_GENERAL_USERTYPE	= 706,
        DATAID_SQM_CODEANALYSIS_USAGE_RULESETSELECTION_FROMPROJECTPROPERTY	= 707,
        DATAID_WINETR_EE_HELP_USAGE	= 708,
        DATAID_WINETR_GENERAL_FEATURE_SEQUENCE	= 709,
        DATAID_WINETR_CODE_COVERAGE_BASIC	= 710,
        DATAID_SQM_CCT_PACKAGEVERSION	= 711,
        DATAID_SQM_CCT_AZURE_TOOLS_ERROR	= 712,
        DATAID_SQM_VSUIAVERSION	= 713,
        DATAID_SQM_CCT_BUILDNUMBER	= 714,
        DATAID_SQM_CCT_BUILDDATE	= 715,
        DATAID_SQM_DOCWELLEXTOPTIONS	= 716,
        DATAID_WINIDE_RESEARCH_PLATFORM_SEARCHSESSIONINVOKED	= 717,
        DATAID_WINIDE_RESEARCH_PLATFORM_WINDOWSTATEONCLOSE	= 718,
        DATAID_WINIDE_RESEARCH_CODESEARCH_SEARCHSESSION	= 719,
        DATAID_WINIDE_RESEARCH_CODESEARCH_RESULTOPENEDINEDITOR	= 720,
        DATAID_WINIDE_RESEARCH_CODESEARCH_PREVIEWLOADTIME	= 721,
        DATAID_WINIDE_RESEARCH_PLATFORM_DEFAULTSCOPESET	= 722,
        DATAID_WINIDE_RESEARCH_CODESEARCH_REFERENCEBARFILTERTOOLTIPUSED	= 723,
        DATAID_WINIDE_RESEARCH_CODESEARCH_REFERENCEBAROPERATORTOOLTIPUSED	= 724,
        DATAID_WINIDE_RESEARCH_CODESEARCH_REFERENCEBARFILTERCLICKED	= 725,
        DATAID_WINIDE_RESEARCH_CODESEARCH_REFERENCEBAROPERATORCLICKED	= 726,
        DATAID_WINIDE_RESEARCH_CODESEARCH_RESULTFILTERCLICKED	= 727,
        DATAID_WINIDE_RESEARCH_CODESEARCH_PREVIEWFILTERCLICKED	= 728,
        DATAID_DP_WINIDE_RESEARCH_PLATFORM_MAXTABCOUNT	= 729,
        DATAID_STRM_WINIDE_RESEARCH_CODESEARCH_PREVIEWFAILED	= 730,
        DATAID_WINETR_SA_OACRVIEWER	= 731,
        DATAID_WINETR_EE_GENERAL_USERALIAS_HASH	= 732,
        DATAID_WINETR_SA_WARNINGSTREAM	= 733,
        DATAID_WINETR_SA_GENERATEDRESULT	= 734,
        DATAID_WINETR_EE_GENERAL_VERSION	= 735,
        DATAID_STRM_HISTORIC_DIAGNOSTIC_EVENTS_CHANGED	= 736,
        DATAID_SQM_STRM_DSWIN_SESSION	= 737,
        DATAID_WINETR_GENERAL_VSSKUS	= 738,
        DATAID_STRM_XAMLFILEINFO	= 739,
        DATAID_STRM_XAMLFEATURES	= 740,
        DATAID_STRM_XAMLPANEUSE	= 741,
        DATAID_STRM_XAMLFEATUREUSE	= 742,
        DATAID_SQM_VSP_IDE_SOLUTION_NAVIGATOR	= 743,
        DATAID_DP_VSP_SNRESCOPEENABLED	= 744,
        DATAID_DP_VSP_SNTOOLTIPENABLED	= 745,
        DATAID_SQM_VSP_IDE_PROPACK	= 746,
        DATAID_DP_VSP_SNEXPANSIONENABLED	= 747,
        DATAID_SQM_WORKFLOWDESIGNER_ACTIVITYUSAGECOUNT	= 748,
        DATAID_SQM_WORKFLOWDESIGNER_FEATUREUSAGECOUNT	= 749,
        DATAID_SQM_DOCWELLEXTPRESET	= 750,
        DATAID_SQM_STRM_DSWIN_SESSION2	= 751,
        DATAID_SQM_VSSTARTUPTIME	= 752,
        DATAID_SQM_TFS_VC_MANUALMERGE	= 753,
        DATAID_SQM_TFS_VC_AUTOMERGE	= 754,
        DATAID_SQM_DP_RIASERVICES_QUERYMETHODCOUNT	= 755,
        DATAID_SQM_DP_RIASERVICES_DOMAINCONTEXTS_RELOADTIME	= 756,
        DATAID_SQM_DP_RIASERVICES_DOMAINCONTEXT_RELOADINTERVAL	= 757,
        DATAID_SQM_DP_RIASERVICES_UI_NOBUILD	= 758,
        DATAID_SQM_DP_RIASERVICES_UI_PARAMETERCOUNT	= 759,
        DATAID_SQM_TFS_VC_SERVERINFORMATION	= 760,
        DATAID_STRM_DEPLOYDETAILS	= 761,
        DATAID_SQM_WAT_PROJECT_ROLES	= 762,
        DATAID_ACTIONID	= 763,
        DATAID_SQM_WAT_PROJECT_ROLES_STRM	= 764,
        DATAID_STRM_PROGRESSIONGRAPHSTATISTICS	= 765,
        DATAID_STRM_STANDARDGRAPHOPERATIONS	= 766,
        DATAID_PROGRESSIONGRAPHCLICKS	= 767,
        DATAID_STRM_PROGRESSIONBROWSERCLICKS	= 768,
        DATAID_STRM_PROGRESSIONACTIONUSAGE	= 769,
        DATAID_STRM_VSTT_LOADUSAGE	= 770,
        DATAID_SYM_NUMBEROFENTITIESINAPP	= 771,
        DATAID_SYM_DEPLOYEDAPPLICATIONTYPE	= 772,
        DATAID_SYM_NUMBEROFSCREENSINAPP	= 773,
        DATAID_SYM_ISINTRINSICDATABASEUSED	= 774,
        DATAID_STRM_DEPLOYMENTSTREAM1	= 775,
        DATAID_STRM_USEDEXTENSIONSSTREAM	= 776,
        DATAID_STRM_USEDTHEMESSTREAM	= 777,
        DATAID_STRM_USESSCREENTEMPLATESTHEME	= 778,
        DATAID_STRM_ATTACHEDSQLDATABASEVERSIONSTREAM	= 779,
        DATAID_SQM_STARTUPAPPBUILDNUMBERSTRING	= 780,
        DATAID_WINIDE_ATMETRICS_WARNINGSTREAM	= 781,
        DATAID_WINIDE_ATMETRICS_PROJECTNAME	= 782,
        DATAID_WINIDE_ATMETRICS_BUILDFLAVORANDSESSIONID	= 783,
        DATAID_WINIDE_ATMETRICS_BRANCHNAME	= 784,
        DATAID_WINIDE_ATMETRICS_LONGESTCOMMONROOT	= 785,
        DATAID_WEBPLAT_DP_USAGE_TIME	= 786,
        DATAID_WEBPLAT_DP_LOCALE	= 787,
        DATAID_WEBPLAT_DP_GENERAL_FEATURE_SEQUENCE	= 788,
        DATAID_WEBPLAT_DP_TIME_IN_WORKSPACES	= 789,
        DATAID_WEBPLAT_DP_SITE_START_TYPE	= 790,
        DATAID_WEBPLAT_DP_SITE_FRAMEWORK	= 791,
        DATAID_WEBPLAT_DP_APP_GALLERY_APP	= 792,
        DATAID_WEBPLAT_DP_APP_INSTALL_TIME	= 793,
        DATAID_WEBPLAT_DP_APP_GALLERY_FAILURE	= 794,
        DATAID_WEBPLAT_DP_WEBPI_INSTALL_TYPE	= 795,
        DATAID_WEBPLAT_DP_FWH_CLICK	= 796,
        DATAID_WEBPLAT_DP_IMPORT_PROFILE	= 797,
        DATAID_WEBPLAT_DP_PUBLISH_PROTOCOL_TYPE	= 798,
        DATAID_WEBPLAT_DP_PUBLISH	= 799,
        DATAID_WEBPLAT_DP_PUBLISH_FAILURE_CODE	= 800,
        DATAID_DP_SETUP_RM_LASTUSERRESPONSE	= 801,
        DATAID_V_SETUP_RM_LASTDIALOGRESPONSETIME	= 802,
        DATAID_DP_SETUP_RM_LASTTIMETOCLOSEAPPS	= 803,
        DATAID_DP_SETUP_RM_TOTALATTEMPTSCOUNT	= 804,
        DATAID_V_SETUP_REBOOT_IGNORED	= 805,
        DATAID_DP_SETUP_RM_INITIAL_APPS_COUNT	= 806,
        DATAID_DP_SETUP_RM_CRITICALAPPSCOUNT	= 807,
        DATAID_DP_SETUP_RM_EXTERNALUI_VER	= 808,
        DATAID_DP_SETUP_RMFILESTREAM	= 809,
        DATAID_DP_SETUP_RMAPPLICATIONSTREAM	= 810,
        DATAID_WEBPLAT_STRM_CMDHISTORY	= 811,
        DATAID_WEBPLAT_STRM_APP_GALLERY_INSTALL	= 812,
        DATAID_WEBPLAT_STRM_PUBLISH_INFO	= 813,
        DATAID_WEBPLAT_STRM_SITE_INFO	= 814,
        DATAID_WEBPLAT_STRM_TIME_IN_WORKSPACES	= 815,
        DATAID_WEBPLAT_STRM_FILE_OPEN	= 816,
        DATAID_WEBPLAT_STRM_DATABASE_CONNECTIONS	= 817,
        DATAID_WEBPLAT_STRM_REPORTS_INFO	= 818,
        DATAID_WEBPLAT_STRM_IMPORT_PROFILE	= 819,
        DATAID_WEBPLAT_DP_OSVERSION	= 820,
        DATAID_SETUP_ACQUISITIONSIZE	= 821,
        DATAID_SETUP_ACQUISITIONTIME	= 822,
        DATAID_SETUP_BUNDLERESULT	= 823,
        DATAID_SETUP_CUSTOMPATH	= 824,
        DATAID_SETUP_FREEDISKSPACE_APP	= 825,
        DATAID_SETUP_MAXDISKSPACE_APP	= 826,
        DATAID_SETUP_MAXDISKSPACE_SYS	= 827,
        DATAID_SETUP_REQUIREDDISKSPACE_APP	= 828,
        DATAID_SETUP_REQUIREDDISKSPACE_SYS	= 829,
        DATAID_SETUP_USEDDISKSPACE_APP	= 830,
        DATAID_SETUP_USEDDISKSPACE_SYS	= 831,
        DATAID_SETUP_FEATUREADMINMAP	= 832,
        DATAID_SETUP_FROMADMINFILE	= 833,
        DATAID_SETUP_FULL	= 834,
        DATAID_SETUP_INITIALFEATUREMAP	= 835,
        DATAID_SETUP_INSTALLTIME	= 836,
        DATAID_SETUP_INTERRUPTCOUNT	= 837,
        DATAID_SETUP_LANGSINSTALLED	= 838,
        DATAID_SETUP_LPINSTALL	= 839,
        DATAID_SETUP_SOURCEPROMPTS	= 840,
        DATAID_SETUP_VMTYPE	= 841,
        DATAID_SETUP_ACQUISITIONSTREAM	= 842,
        DATAID_SETUP_INTERRUPTSTREAM	= 843,
        DATAID_SETUP_PACKAGESTREAM	= 844,
        DATAID_STRM_VS_EXTENSIONS_INSTALLED	= 845,
        DATAID_STRM_VSTLM_FB_FBTOOLSESSION1	= 846,
        DATAID_STRM_VSTLM_FB_FBUSERSTORYSESSION1	= 847,
        DATAID_WEBPLAT_STRM_APP_GALLERY_INSTALL2	= 848,
        DATAID_WEBPLAT_STRM_PUBLISH_INFO2	= 849,
        DATAID_SQM_CV_LAUNCHES_ATTACH	= 850,
        DATAID_SQM_CV_LAUNCHES_START	= 851,
        DATAID_SQM_CV_LAUNCHES_LAUNCH	= 852,
        DATAID_SQM_CV_LAUNCHES_OPEN	= 853,
        DATAID_SQM_CV_LAUNCHES_SETTINGS	= 854,
        DATAID_SQM_CV_LAUNCHES_ADDSDK	= 855,
        DATAID_SQM_CV_VIEW_BEHAVIOR	= 856,
        DATAID_SQM_CV_TRACE_DATA	= 857,
        DATAID_STRM_V----TENSIONINSTALLED	= 858,
        DATAID_STRM_V----TENSIONUSED	= 859,
        DATAID_DP_WPPROJECTVERSION	= 860,
        DATAID_HELPVIEWER_OSVERSION	= 861,
        DATAID_HELPVIEWER_OSSERVICEPACK	= 862,
        DATAID_HELPVIEWER_HLPVIEWERVERSION	= 863,
        DATAID_STRM_BIZAPPSSHAREPOINTPROJECTS_DEV11	= 864,
        DATAID_STRM_BIZAPPSSHAREPOINTITEMS_DEV11	= 865,
        DATAID_HELPVIEWER_OFFLINEF1	= 866,
        DATAID_HELPVIEWER_TOPICNAVSOURCE	= 867,
        DATAID_CAMANO_ISHOSTEDTFS	= 868,
        DATAID_VSHELP_FIRSTRUNHELPINSTALLSELECTION	= 869,
        DATAID_VSHELP_SETHELPPREFERENCE	= 870,
        DATAID_STRM_WPPROJECTUPGRADE	= 871,
        DATAID_STRM_DP_VSTT_UT_SESSIONINFO	= 872,
        DATAID_STRM_VSTT_XT1	= 873,
        DATAID_VSTLM_WIN8	= 874,
        DATAID_STRM_WPDEVICEUNLOCKTOOL	= 875,
        DATAID_STRM_WPPROFILERDATA	= 876,
        DATAID_STRM_WPPROFILERANALYZERS	= 877,
        DATAID_SETUP_DEFAULTFEATUREMAP	= 878,
        DATAID_DP_WINSIM_OSVERSION	= 879,
        DATAID_DP_WINSIM_OSSERVICEPACK	= 880,
        DATAID_DP_WINSIM_OSSKU	= 881,
        DATAID_DP_WINSIM_CPUCOUNT	= 882,
        DATAID_DP_WINSIM_PROCFREQ	= 883,
        DATAID_DP_WINSIM_MEMORY	= 884,
        DATAID_DP_WINSIM_DISPLAYCOUNT	= 885,
        DATAID_DP_WINSIM_ISREMOTEDESKTOP	= 886,
        DATAID_DP_WINSIM_ISVMHOST	= 887,
        DATAID_DP_WINSIM_USERTYPE	= 888,
        DATAID_DP_WINSIM_STARTTIME	= 889,
        DATAID_DP_WINSIM_SHUTDOWNTIME	= 890,
        DATAID_DP_WINSIM_ALREADYRUNNING	= 891,
        DATAID_DP_WINSIM_TOUCHDEVICECOUNT	= 892,
        DATAID_DP_WINSIM_CMDSTREAM	= 893,
        DATAID_DP_WINSIM_LOCSENSORCOUNT	= 894,
        DATAID_DP_WINSIM_LOCSENSORENABLED	= 895,
        DATAID_DP_WINSIM_OSBUILD	= 896,
        DATAID_DP_STREAM_WINSIM_DIMENSIONS	= 897,
        DATAID_STRM_WPMARKETPLACETESTKIT	= 898,
        DATAID_RTDISTICTUSERS	= 899,
        DATAID_DEPLOYMENTINFO11	= 900,
        DATAID_TFSAO_SETUPOPTIONS11	= 901,
        DATAID_PHYSICALNUMBERCPU11	= 902,
        DATAID_PROCCLOCKSPEED11	= 903,
        DATAID_PROCFAMILY11	= 904,
        DATAID_PROCDATAWIDTH11	= 905,
        DATAID_RAM11	= 906,
        DATAID_STRM_VSTLM_FB_FBTOOLSESSION	= 907,
        DATAID_STRM_VSTLM_FB_FBUSERSTORYSESSION	= 908,
        DATAID_STRM_VSTT_XT_USERSTORYSESSION	= 909,
        DATAID_CPULOGICALCOUNT11	= 910,
        DATAID_TFSAO_11_FULLCONFIGRESULTS	= 911,
        DATAID_TFSAO_RUNTIME11	= 912,
        DATAID_STRM_DEBUGGER_LAUNCH	= 913,
        DATAID_STRM_GETWIN8DEVLICENSE	= 914,
        DATAID_STRM_WIN8APPDEPLOYFAILURE	= 915,
        DATAID_STRM_WIN8APPDEPLOYPERFORMANCE	= 916,
        DATAID_WEBPLAT_DP_LOCALE_2	= 917,
        DATAID_SQM_CODEANALYSIS_USAGE_NOVIOLATIONBUILDS	= 918,
        DATAID_SQM_CODEANALYSIS_ANALYSIS_NEWVIOLATIONS	= 919,
        DATAID_STRM_VSTLM_MFB_SESSION	= 920,
        DATAID_STRM_JAVASCRIPT_COMPLETIONVSFILEIDENTIFIERLIST	= 921,
        DATAID_STRM_JAVASCRIPT_GOTODEFINITIONNAVIGATION	= 922,
        DATAID_STRM_WAT_PROJECT_CREATION	= 923,
        DATAID_STRM_WAT_PROJECT_ROLES	= 924,
        DATAID_WEBPLAT_DP_CPU_COUNT	= 925,
        DATAID_WEBPLAT_DP_DISPLAYCOUNT	= 926,
        DATAID_WEBPLAT_DP_MEMORY	= 927,
        DATAID_WEBPLAT_DP_STARTUP_TIME	= 928,
        DATAID_WEBPLAT_STRM_OPENED_AFTER_FIRST_LAUNCH	= 929,
        DATAID_STRM_WAT_PROJECT_COUNT	= 930,
        DATAID_STRM_WAT_ROLE_TEMPLATE	= 931,
        DATAID_WEBPLAT_STRM_FILE_ADDED	= 932,
        DATAID_WEBPLAT_STRM_NUGET_PACKAGES	= 933,
        DATAID_WEBPLAT_STRM_SITE_OPEN_TIME	= 934,
        DATAID_STRM_PROJECTMIGRATE	= 935,
        DATAID_WEBPLAT_STRM_EXTENSION_GALLERY	= 936,
        DATAID_WEBPLAT_DP_REMOTE_TAB	= 937,
        DATAID_WEBPLAT_STRM_REMOTE_BUTTONS	= 938,
        DATAID_WEBPLAT_STRM_REMOTE_FILE	= 939,
        DATAID_WEBPLAT_STRM_LEARN_OPEN	= 940,
        DATAID_WEBPLAT_STRM_REPORTS_ADVANCED_SETTINGS	= 941,
        DATAID_WEBPLAT_STRM_LEARN_FEED	= 942,
        DATAID_WEBPLAT_DP_LEARN_LINKS_CLICK	= 943,
        DATAID_WEBPLAT_STRM_DISPLAY_RESOLUTION	= 944,
        DATAID_STRM_DEBUGCANVASOPTIONS	= 945,
        DATAID_STRM_WAT_PACKAGE_DETAILS	= 946,
        DATAID_STRM_ERRORLISTFILTER	= 947,
        DATAID_STRM_QUICKLAUNCH_SHOWPREVIOUSRESULTS	= 948,
        DATAID_STRM_WINDOWMGMT_PREVIEWTAB	= 949,
        DATAID_STRM_WINDOWMGMT_PREVIEWTAB_FINDRESULTS	= 950,
        DATAID_STRM_WINDOWMGMT_PINNEDINSEPERATEROW	= 951,
        DATAID_STRM_WINDOWMGMT_SHOWPINBUTTONINUNPINNEDTABS	= 952,
        DATAID_STRM_WINDOWMGMT_PINSTATUSMAINTAIN	= 953,
        DATAID_STRM_WINDOWMGMT_INSERTNEWTABTORIGHT	= 954,
        DATAID_STRM_WINDOWMGMT_FLOATINGTABWELLSONTOP	= 955,
        DATAID_STRM_WINDOWMGMT_FLOATINGTOOLWINDOWSONTOP	= 956,
        DATAID_DP_VSTT_RNP_APPLICATIONTYPE	= 957,
        DATAID_STRM_TOOLSOPT_WINDOWMGMT_PREVIEWTAB_SOLEXP	= 958,
        DATAID_STRM_QUICKLAUNCH_CATEGORYSELECTED	= 959,
        DATAID_STRM_OPTIONSTHEMECHANGES	= 960,
        DATAID_STRM_SOLEXP_PIVOTRELATIONSHIPDYNAMICMENU	= 961,
        DATAID_STRM_SOLEXP_SEARCHSTARTEDCOUNT	= 962,
        DATAID_STRM_TOOLSOPT_QUICKLAUNCH_ENABLEDISABLE	= 963,
        DATAID_STRM_SOLUTONLOAD	= 964,
        DATAID_STRM_PROJECTTYPE	= 965,
        DATAID_STRM_INITIALIZEDTWGUIDS	= 966,
        DATAID_GPU_THREADS_USAGE	= 967,
        DATAID_PARALLEL_WATCH_USAGE	= 968,
        DATAID_THREADS_IN_SOURCE_TOOLTIP_USAGE	= 969,
        DATAID_SETUP_APPLYTIME	= 970,
        DATAID_GPU_DEBUGGING_SESSION	= 971,
        DATAID_STRM_QUICKLAUNCH_SEARCHSTARTCOUNT	= 972,
        DATAID_STRM_QUICKLAUNCH_FOCUSINPUTTYPE	= 973,
        DATAID_VSTLM_WIN8_APP_DEPLOY	= 974,
        DATAID_STRM_SOLUTONLOAD2	= 975,
        DATAID_STRM_INITIALIZEDTWGUIDS2	= 976,
        DATAID_STRM_PROJECTTYPE2	= 977,
        DATAID_DP_WINSIM_LOGINPROMPTS	= 978,
        DATAID_DP_SETUP_FAILCOUNT	= 979,
        DATAID_DP_SETUP_CURRENTPAYLOAD	= 980,
        DATAID_DP_SETUP_USINGREDIRECTOR	= 981,
        DATAID_DP_APPVVERSION	= 982,
        DATAID_DP_STRM_TOOLSTREAM	= 983,
        DATAID_DP_SPINSTALLER_APPLICATIONNAME	= 984,
        DATAID_STRM_WAT_PACKAGE_DETAILS_17	= 985,
        DATAID_HELPVIEWER_USERTYPE	= 986,
        DATAID_STRM_WINDOWMGMT_PREVIEWTABCOUNT	= 987,
        DATAID_STRM_WAT_ROLE_TEMPLATE_WITH_GUID	= 988,
        DATAID_DP_ISXRAYENABLED	= 989,
        DATAID_STRM_XRAYEXTENSIONSIGNORED	= 990,
        DATAID_STRM_XRAYEXTENSIONLOADTIME	= 991,
        DATAID_STRM_WAT_ROLE_CACHE	= 992,
        DATAID_STRM_WAT_PROJECT_CACHE	= 993,
        DATAID_DP_WPPRODUCTID	= 994,
        DATAID_STRM_XRAYLOADTIMES	= 995,
        DATAID_DP_SETUP_TOOLRESULT	= 996,
        DATAID_STRM_WPSIMULATIONDATA	= 997,
        DATAID_STRM_TB_ITEMUSED	= 998,
        DATAID_STRM_TB_REFRESH	= 999,
        DATAID_DP_TB_CHOOSTBBROWSECOUNT	= 1000,
        DATAID_STRM_TB_CACHEREBUILDTIME	= 1001,
        DATAID_DP_TB_OPERATIONFLAGS	= 1002,
        DATAID_DP_TB_OPERATION_ADDTABCOUNT	= 1003,
        DATAID_DP_TB_OPERATION_REMOVETABCOUNT	= 1004,
        DATAID_DP_TB_OPERATION_RENAMETABCOUNT	= 1005,
        DATAID_DP_TB_OPERATION_REORDERTABCOUNT	= 1006,
        DATAID_DP_TB_OPERATION_MOVEITEMWITHINTABCOUNT	= 1007,
        DATAID_DP_TB_OPERATION_MOVEITEMBETWEENTABSCOUNT	= 1008,
        DATAID_STRM_WPADDPROJECTREFERENCE	= 1009,
        DATAID_STRM_PROGRESSIONGRAPHUSERACTIONS	= 1010,
        DATAID_DP_WPMACHINESLATSTATE	= 1011,
        DATAID_SQM_OSUSERLOCALE	= 1012,
        DATAID_SQM_USEROSUILOCALE	= 1013,
        DATAID_STRM_WPPROFILERWARNINGS	= 1014,
        DATAID_SQM_PROFILER_LAUNCH_TARGET	= 1015,
        DATAID_SQM_PROFILER_NUM_LOCAL_LAUNCHES	= 1016,
        DATAID_SQM_PROFILER_NUM_SIMULATOR_LAUNCHES	= 1017,
        DATAID_SQM_PROFILER_NUM_REMOTE_LAUNCHES	= 1018,
        DATAID_SQM_PROFILER_NUM_METRO_LAUNCHES	= 1019,
        DATAID_SQM_PROFILER_NUM_CLASSIC_LAUNCHES	= 1020,
        DATAID_STRM_VSWEBPUBLISH_PUBLISHMETHOD	= 1021,
        DATAID_STRM_ERRORLIST_TOGGLESTATE	= 1022,
        DATAID_STRM_EXPSQM	= 1023,
        DATAID_STRM_LAUNCHELAPSEDTIME	= 1024,
        DATAID_STRM_WPDEPLOYDEBUGDATA	= 1025,
        DATAID_DP_WPSAVEDSTATECREATION	= 1026,
        DATAID_STRM_WPAPPMONLINKCLICKED	= 1027,
        DATAID_STRM_WPAPPMONALERTCOUNT	= 1028,
        DATAID_STRM_WPAPPMONDETAILEDVIEWNAVIGATION	= 1029,
        DATAID_STRM_WPPROJECTCREATE	= 1030,
        DATAID_STRM_PROJECTFILEDETAILS	= 1031,
        DATAID_STRM_PROJECTLIBRARIES	= 1032,
        DATAID_STRM_PROJECTPROPERTIES	= 1033,
        DATAID_STRM_PROJECTREFERENCES	= 1034,
        DATAID_STRM_SOLUTIONFILEDETAILS	= 1035,
        DATAID_DP_VC_BUILDTIMETEST	= 1036,
        DATAID_DP_WAT_SUBSCRIPTIONS_ALL	= 1037,
        DATAID_DP_WAT_SUBSCRIPTIONS_DEFAULT_ENDPOINT	= 1038,
        DATAID_STRM_APPPACKAGEWIZARD	= 1039,
        DATAID_STRM_APPPACKAGEBUILDERRORS	= 1040,
        DATAID_DP_APPPACKAGEBUILDSUCCESSWITHGENERATEDMANIFEST	= 1041,
        DATAID_APPPACKAGEBUILDSUCCESSWITHCUSTOMMANIFEST	= 1042,
        DATAID_DP_APPPACKAGEBUILDFAILWITHGENERATEDMANIFEST	= 1043,
        DATAID_DP_APPPACKAGEBUILDFAILWITHCUSTOMMANIFEST	= 1044,
        DATAID_DP_MANIFESTDESIGNERINTERACTION	= 1045,
        DATAID_DP_MANIFESTDESIGNERCAPABILITYAPI	= 1046,
        DATAID_STRM_DEBUGGER_NOSOURCEWINDOWREASON	= 1047,
        DATAID_STRM_DEBUGGER_DUMPSUMMARY	= 1048,
        DATAID_STRM_MULTISCALEIMAGEINSTANCE	= 1049,
        DATAID_STRM_MANIFESTMULTISCALEIMAGEINSTANCE	= 1050,
        DATAID_JSSNAPSHOTINFO	= 1051,
        DATAID_ZEPHYRSNAPSHOTVIEWS	= 1052,
        DATAID_JSSNAPSHOTDIFFINFO	= 1053,
        DATAID_DP_VSTT_RNP_BROWSERTYPE	= 1054,
        DATAID_DP_STARTUPASSETTYPE	= 1055,
        DATAID_DP_STARTUPTYPE	= 1056,
        DATAID_SCENARIOPART	= 1057,
        DATAID_DP_SETUP_FIXESSTATUS	= 1058,
        DATAID_DP_SETUP_FIXESSUCCESSFUL	= 1059,
        DATAID_STRM_LINKERTHROUGHPUT	= 1060,
        DATAID_DP_TOOLFIXSTATUS	= 1061,
        DATAID_STRM_VC_LINKER_SWITCH	= 1062,
        DATAID_DP_SETUP_VSONLINE	= 1063,
        DATAID_STRM_VC_LINKER_SWITCHES	= 1064,
        DATAID_STRM_XAMLDESIGNERCOMMAND	= 1065,
        DATAID_EXTENSIONMANAGERAUTOCHECKUPDATES	= 1066,
        DATAID_STRM_XAMLDESIGNERDESIGNERSTARTTIME	= 1067,
        DATAID_STRM_DESIGNER_VIEW_TIME	= 1068,
        DATAID_EDITOR_VIEW_TIME	= 1069,
        DATAID_SPLIT_VIEW_TIME	= 1070,
        DATAID_STRM_INTELLISENSE_STARTTIME	= 1071,
        DATAID_STRM_VC_LINKER_PARENTPROCESS	= 1072,
        DATAID_STRM_VC_LINKER_HOST_TARGET	= 1073,
        DATAID_STRM_DESIGNER_VIEWTIME	= 1074,
        DATAID_STRM_SPLIT_VIEWTIME	= 1075,
        DATAID_STRM_EDITOR_VIEWTIME	= 1076,
        DATAID_STRM_VC_LINKER_DIAGNOSTICS	= 1077,
        DATAID_STRM_LINKER_THROUGHPUT	= 1078,
        DATAID_WEBPLAT_STRM_GIT_OPEN	= 1079,
        DATAID_STREAM_TEXTEDITOROPTIONS	= 1080,
        DATAID_STRM_XAML_DESIGNER_LOADTIME	= 1081,
        DATAID_STRM_XAML_DOC_VIEWTIME	= 1082,
        DATAID_STRM_ROAMINGSETTINGS_PERFORMANCE	= 1083,
        DATAID_WEBPLAT_STRM_CMD	= 1084,
        DATAID_WEBPLAT_STRM_GIT_ADD_BRANCH	= 1085,
        DATAID_WEBPLAT_STRM_GIT_ADD_REMOTE	= 1086,
        DATAID_WEBPLAT_STRM_GIT_INIT	= 1087,
        DATAID_WEBPLAT_STRM_MY_SITES	= 1088,
        DATAID_WEBPLAT_STRM_OPEN_FROM_FOLDER	= 1089,
        DATAID_WEBPLAT_STRM_OPEN_FROM_MY_SITES	= 1090,
        DATAID_WEBPLAT_STRM_OPEN_FROM_PORTAL	= 1091,
        DATAID_WEBPLAT_STRM_OPEN_FROM_REMOTE	= 1092,
        DATAID_WEBPLAT_STRM_PROVISION_SKIP	= 1093,
        DATAID_WEBPLAT_STRM_SIGN_IN	= 1094,
        DATAID_WEBPLAT_STRM_SIGN_IN_RESULT	= 1095,
        DATAID_WEBPLAT_STRM_SIGN_OUT	= 1096,
        DATAID_WEBPLAT_STRM_SKIP_SIGN_IN	= 1097,
        DATAID_WEBPLAT_STRM_TFS_ADD_TO_PROJECT	= 1098,
        DATAID_WEBPLAT_STRM_TFS_OPEN	= 1099,
        DATAID_STREAM_NAVTO2_USAGEPATTERNS	= 1100,
        DATAID_WEBPLAT_STRM_PROVISION	= 1101,
        DATAID_WEBPLAT_STRM_IMPORT_CERT	= 1102,
        DATAID_STRM_DEPLOYMENTSTREAM2	= 1103,
        DATAID_DP_VSIINSTALLCOUNT	= 1104,
        DATAID_STRM_VSIINSTALLCONTENTS	= 1105,
        DATAID_WEBPLAT_STRM_SUBSCRIBE	= 1106,
        DATAID_MVC	= 1107,
        DATAID_STRM_HISTORIC_LOG_OPEN3	= 1108,
        DATAID_STRM_SPTOOLSPROJECTCONTENTS	= 1109,
        DATAID_WEBPLAT_STRM_GIT_OPEN_2	= 1110,
        DATAID_STRM_SPTOOLSERRORS	= 1111,
        DATAID_STRM_VC_CASABLANCA_HEADERS	= 1112,
        DATAID_STRM_ASQM1	= 1113,
        DATAID_STRM_ASQM2	= 1114,
        DATAID_SQM_DISPLAYXY	= 1115,
        DATAID_SQM_DISPLAYVIRTUALXY	= 1116,
        DATAID_MAX	= 1117
    } 	vsSqmDatapoint;



extern RPC_IF_HANDLE __MIDL_itf_vslog_0000_0001_v0_0_c_ifspec;
extern RPC_IF_HANDLE __MIDL_itf_vslog_0000_0001_v0_0_s_ifspec;

#ifndef __IVsSqm_INTERFACE_DEFINED__
#define __IVsSqm_INTERFACE_DEFINED__

/* interface IVsSqm */
/* [object][unique][helpstring][uuid] */ 


EXTERN_C const IID IID_IVsSqm;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    MIDL_INTERFACE("C1F63D0C-4CAE-4907-BE74-EEB75D386ECB")
    IVsSqm : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE GetSessionStartTime( 
            /* [out] */ __RPC__out FILETIME *pftTime) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetFlags( 
            /* [out] */ __RPC__out DWORD *pdwFlags) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE SetFlags( 
            /* [in] */ DWORD dwFlags) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE ClearFlags( 
            /* [in] */ DWORD dwFlags) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE AddItemToStream( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE SetDatapoint( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetDatapoint( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [out] */ __RPC__out LPDWORD pdwValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE EnterTaggedAssert( 
            /* [in] */ DWORD dwTag,
            /* [in] */ DWORD dwPossibleBuild,
            /* [in] */ DWORD dwActualBuild) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE RecordCmdData( 
            /* [in] */ __RPC__in const GUID *pguidCmdGroup,
            /* [in] */ DWORD dwCmdId,
            /* [in] */ DWORD dwValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetHashOfGuid( 
            /* [in] */ __RPC__in const GUID *pguidToHash,
            /* [out] */ __RPC__out DWORD *dwResultantHash) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetHashOfString( 
            /* [in] */ __RPC__in const BSTR strToHash,
            /* [out] */ __RPC__out DWORD *dwResultantHash) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE IncrementDatapoint( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE SetDatapointBits( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE SetDatapointIfMax( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE SetDatapointIfMin( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE AddToDatapointAverage( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE StartDatapointTimer( 
            /* [in] */ vsSqmDatapoint stDatapoint) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE RecordDatapointTimer( 
            /* [in] */ vsSqmDatapoint stDatapoint) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE AccumulateDatapointTimer( 
            /* [in] */ vsSqmDatapoint stDatapoint) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE AddTimerToDatapointAverage( 
            /* [in] */ vsSqmDatapoint stDatapoint) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE AddArrayToStream( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [size_is][in] */ __RPC__in_ecount_full(iCount) DWORD dwArray[  ],
            /* [in] */ int iCount) = 0;
        
    };
    
    
#else 	/* C style interface */

    typedef struct IVsSqmVtbl
    {
        BEGIN_INTERFACE
        
        HRESULT ( STDMETHODCALLTYPE *QueryInterface )( 
            __RPC__in IVsSqm * This,
            /* [in] */ __RPC__in REFIID riid,
            /* [annotation][iid_is][out] */ 
            _COM_Outptr_  void **ppvObject);
        
        ULONG ( STDMETHODCALLTYPE *AddRef )( 
            __RPC__in IVsSqm * This);
        
        ULONG ( STDMETHODCALLTYPE *Release )( 
            __RPC__in IVsSqm * This);
        
        HRESULT ( STDMETHODCALLTYPE *GetSessionStartTime )( 
            __RPC__in IVsSqm * This,
            /* [out] */ __RPC__out FILETIME *pftTime);
        
        HRESULT ( STDMETHODCALLTYPE *GetFlags )( 
            __RPC__in IVsSqm * This,
            /* [out] */ __RPC__out DWORD *pdwFlags);
        
        HRESULT ( STDMETHODCALLTYPE *SetFlags )( 
            __RPC__in IVsSqm * This,
            /* [in] */ DWORD dwFlags);
        
        HRESULT ( STDMETHODCALLTYPE *ClearFlags )( 
            __RPC__in IVsSqm * This,
            /* [in] */ DWORD dwFlags);
        
        HRESULT ( STDMETHODCALLTYPE *AddItemToStream )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue);
        
        HRESULT ( STDMETHODCALLTYPE *SetDatapoint )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue);
        
        HRESULT ( STDMETHODCALLTYPE *GetDatapoint )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [out] */ __RPC__out LPDWORD pdwValue);
        
        HRESULT ( STDMETHODCALLTYPE *EnterTaggedAssert )( 
            __RPC__in IVsSqm * This,
            /* [in] */ DWORD dwTag,
            /* [in] */ DWORD dwPossibleBuild,
            /* [in] */ DWORD dwActualBuild);
        
        HRESULT ( STDMETHODCALLTYPE *RecordCmdData )( 
            __RPC__in IVsSqm * This,
            /* [in] */ __RPC__in const GUID *pguidCmdGroup,
            /* [in] */ DWORD dwCmdId,
            /* [in] */ DWORD dwValue);
        
        HRESULT ( STDMETHODCALLTYPE *GetHashOfGuid )( 
            __RPC__in IVsSqm * This,
            /* [in] */ __RPC__in const GUID *pguidToHash,
            /* [out] */ __RPC__out DWORD *dwResultantHash);
        
        HRESULT ( STDMETHODCALLTYPE *GetHashOfString )( 
            __RPC__in IVsSqm * This,
            /* [in] */ __RPC__in const BSTR strToHash,
            /* [out] */ __RPC__out DWORD *dwResultantHash);
        
        HRESULT ( STDMETHODCALLTYPE *IncrementDatapoint )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue);
        
        HRESULT ( STDMETHODCALLTYPE *SetDatapointBits )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue);
        
        HRESULT ( STDMETHODCALLTYPE *SetDatapointIfMax )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue);
        
        HRESULT ( STDMETHODCALLTYPE *SetDatapointIfMin )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue);
        
        HRESULT ( STDMETHODCALLTYPE *AddToDatapointAverage )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD dwValue);
        
        HRESULT ( STDMETHODCALLTYPE *StartDatapointTimer )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint);
        
        HRESULT ( STDMETHODCALLTYPE *RecordDatapointTimer )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint);
        
        HRESULT ( STDMETHODCALLTYPE *AccumulateDatapointTimer )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint);
        
        HRESULT ( STDMETHODCALLTYPE *AddTimerToDatapointAverage )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint);
        
        HRESULT ( STDMETHODCALLTYPE *AddArrayToStream )( 
            __RPC__in IVsSqm * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [size_is][in] */ __RPC__in_ecount_full(iCount) DWORD dwArray[  ],
            /* [in] */ int iCount);
        
        END_INTERFACE
    } IVsSqmVtbl;

    interface IVsSqm
    {
        CONST_VTBL struct IVsSqmVtbl *lpVtbl;
    };

    

#ifdef COBJMACROS


#define IVsSqm_QueryInterface(This,riid,ppvObject)	\
    ( (This)->lpVtbl -> QueryInterface(This,riid,ppvObject) ) 

#define IVsSqm_AddRef(This)	\
    ( (This)->lpVtbl -> AddRef(This) ) 

#define IVsSqm_Release(This)	\
    ( (This)->lpVtbl -> Release(This) ) 


#define IVsSqm_GetSessionStartTime(This,pftTime)	\
    ( (This)->lpVtbl -> GetSessionStartTime(This,pftTime) ) 

#define IVsSqm_GetFlags(This,pdwFlags)	\
    ( (This)->lpVtbl -> GetFlags(This,pdwFlags) ) 

#define IVsSqm_SetFlags(This,dwFlags)	\
    ( (This)->lpVtbl -> SetFlags(This,dwFlags) ) 

#define IVsSqm_ClearFlags(This,dwFlags)	\
    ( (This)->lpVtbl -> ClearFlags(This,dwFlags) ) 

#define IVsSqm_AddItemToStream(This,stDatapoint,dwValue)	\
    ( (This)->lpVtbl -> AddItemToStream(This,stDatapoint,dwValue) ) 

#define IVsSqm_SetDatapoint(This,stDatapoint,dwValue)	\
    ( (This)->lpVtbl -> SetDatapoint(This,stDatapoint,dwValue) ) 

#define IVsSqm_GetDatapoint(This,stDatapoint,pdwValue)	\
    ( (This)->lpVtbl -> GetDatapoint(This,stDatapoint,pdwValue) ) 

#define IVsSqm_EnterTaggedAssert(This,dwTag,dwPossibleBuild,dwActualBuild)	\
    ( (This)->lpVtbl -> EnterTaggedAssert(This,dwTag,dwPossibleBuild,dwActualBuild) ) 

#define IVsSqm_RecordCmdData(This,pguidCmdGroup,dwCmdId,dwValue)	\
    ( (This)->lpVtbl -> RecordCmdData(This,pguidCmdGroup,dwCmdId,dwValue) ) 

#define IVsSqm_GetHashOfGuid(This,pguidToHash,dwResultantHash)	\
    ( (This)->lpVtbl -> GetHashOfGuid(This,pguidToHash,dwResultantHash) ) 

#define IVsSqm_GetHashOfString(This,strToHash,dwResultantHash)	\
    ( (This)->lpVtbl -> GetHashOfString(This,strToHash,dwResultantHash) ) 

#define IVsSqm_IncrementDatapoint(This,stDatapoint,dwValue)	\
    ( (This)->lpVtbl -> IncrementDatapoint(This,stDatapoint,dwValue) ) 

#define IVsSqm_SetDatapointBits(This,stDatapoint,dwValue)	\
    ( (This)->lpVtbl -> SetDatapointBits(This,stDatapoint,dwValue) ) 

#define IVsSqm_SetDatapointIfMax(This,stDatapoint,dwValue)	\
    ( (This)->lpVtbl -> SetDatapointIfMax(This,stDatapoint,dwValue) ) 

#define IVsSqm_SetDatapointIfMin(This,stDatapoint,dwValue)	\
    ( (This)->lpVtbl -> SetDatapointIfMin(This,stDatapoint,dwValue) ) 

#define IVsSqm_AddToDatapointAverage(This,stDatapoint,dwValue)	\
    ( (This)->lpVtbl -> AddToDatapointAverage(This,stDatapoint,dwValue) ) 

#define IVsSqm_StartDatapointTimer(This,stDatapoint)	\
    ( (This)->lpVtbl -> StartDatapointTimer(This,stDatapoint) ) 

#define IVsSqm_RecordDatapointTimer(This,stDatapoint)	\
    ( (This)->lpVtbl -> RecordDatapointTimer(This,stDatapoint) ) 

#define IVsSqm_AccumulateDatapointTimer(This,stDatapoint)	\
    ( (This)->lpVtbl -> AccumulateDatapointTimer(This,stDatapoint) ) 

#define IVsSqm_AddTimerToDatapointAverage(This,stDatapoint)	\
    ( (This)->lpVtbl -> AddTimerToDatapointAverage(This,stDatapoint) ) 

#define IVsSqm_AddArrayToStream(This,stDatapoint,dwArray,iCount)	\
    ( (This)->lpVtbl -> AddArrayToStream(This,stDatapoint,dwArray,iCount) ) 

#endif /* COBJMACROS */


#endif 	/* C style interface */




#endif 	/* __IVsSqm_INTERFACE_DEFINED__ */


#ifndef __IVsSqm2_INTERFACE_DEFINED__
#define __IVsSqm2_INTERFACE_DEFINED__

/* interface IVsSqm2 */
/* [object][unique][helpstring][uuid] */ 


EXTERN_C const IID IID_IVsSqm2;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    MIDL_INTERFACE("BE5F55EB-F02D-4217-BCB6-A290800AF6C4")
    IVsSqm2 : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE SetBoolDatapoint( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ BOOL fValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE SetStringDatapoint( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ __RPC__in const BSTR strValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE AddToStreamDWord( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD cTuple,
            /* [in] */ DWORD dwValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE AddToStreamString( 
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD cTuple,
            /* [in] */ __RPC__in const BSTR strValue) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetObfuscatedString( 
            /* [in] */ __RPC__in const BSTR strInput,
            /* [out] */ __RPC__deref_out_opt BSTR *pstrOutput) = 0;
        
    };
    
    
#else 	/* C style interface */

    typedef struct IVsSqm2Vtbl
    {
        BEGIN_INTERFACE
        
        HRESULT ( STDMETHODCALLTYPE *QueryInterface )( 
            __RPC__in IVsSqm2 * This,
            /* [in] */ __RPC__in REFIID riid,
            /* [annotation][iid_is][out] */ 
            _COM_Outptr_  void **ppvObject);
        
        ULONG ( STDMETHODCALLTYPE *AddRef )( 
            __RPC__in IVsSqm2 * This);
        
        ULONG ( STDMETHODCALLTYPE *Release )( 
            __RPC__in IVsSqm2 * This);
        
        HRESULT ( STDMETHODCALLTYPE *SetBoolDatapoint )( 
            __RPC__in IVsSqm2 * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ BOOL fValue);
        
        HRESULT ( STDMETHODCALLTYPE *SetStringDatapoint )( 
            __RPC__in IVsSqm2 * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ __RPC__in const BSTR strValue);
        
        HRESULT ( STDMETHODCALLTYPE *AddToStreamDWord )( 
            __RPC__in IVsSqm2 * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD cTuple,
            /* [in] */ DWORD dwValue);
        
        HRESULT ( STDMETHODCALLTYPE *AddToStreamString )( 
            __RPC__in IVsSqm2 * This,
            /* [in] */ vsSqmDatapoint stDatapoint,
            /* [in] */ DWORD cTuple,
            /* [in] */ __RPC__in const BSTR strValue);
        
        HRESULT ( STDMETHODCALLTYPE *GetObfuscatedString )( 
            __RPC__in IVsSqm2 * This,
            /* [in] */ __RPC__in const BSTR strInput,
            /* [out] */ __RPC__deref_out_opt BSTR *pstrOutput);
        
        END_INTERFACE
    } IVsSqm2Vtbl;

    interface IVsSqm2
    {
        CONST_VTBL struct IVsSqm2Vtbl *lpVtbl;
    };

    

#ifdef COBJMACROS


#define IVsSqm2_QueryInterface(This,riid,ppvObject)	\
    ( (This)->lpVtbl -> QueryInterface(This,riid,ppvObject) ) 

#define IVsSqm2_AddRef(This)	\
    ( (This)->lpVtbl -> AddRef(This) ) 

#define IVsSqm2_Release(This)	\
    ( (This)->lpVtbl -> Release(This) ) 


#define IVsSqm2_SetBoolDatapoint(This,stDatapoint,fValue)	\
    ( (This)->lpVtbl -> SetBoolDatapoint(This,stDatapoint,fValue) ) 

#define IVsSqm2_SetStringDatapoint(This,stDatapoint,strValue)	\
    ( (This)->lpVtbl -> SetStringDatapoint(This,stDatapoint,strValue) ) 

#define IVsSqm2_AddToStreamDWord(This,stDatapoint,cTuple,dwValue)	\
    ( (This)->lpVtbl -> AddToStreamDWord(This,stDatapoint,cTuple,dwValue) ) 

#define IVsSqm2_AddToStreamString(This,stDatapoint,cTuple,strValue)	\
    ( (This)->lpVtbl -> AddToStreamString(This,stDatapoint,cTuple,strValue) ) 

#define IVsSqm2_GetObfuscatedString(This,strInput,pstrOutput)	\
    ( (This)->lpVtbl -> GetObfuscatedString(This,strInput,pstrOutput) ) 

#endif /* COBJMACROS */


#endif 	/* C style interface */




#endif 	/* __IVsSqm2_INTERFACE_DEFINED__ */


#ifndef __IVsSqmOptinManager_INTERFACE_DEFINED__
#define __IVsSqmOptinManager_INTERFACE_DEFINED__

/* interface IVsSqmOptinManager */
/* [object][unique][helpstring][uuid] */ 


EXTERN_C const IID IID_IVsSqmOptinManager;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    MIDL_INTERFACE("16be4288-950b-4265-b0dc-280b89ca9979")
    IVsSqmOptinManager : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE GetOptinStatus( 
            /* [out] */ __RPC__out BOOL *pOptinStatus,
            /* [out] */ __RPC__out BOOL *pPreferences) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE SetOptinStatus( 
            /* [in] */ BOOL OptinStatus) = 0;
        
    };
    
    
#else 	/* C style interface */

    typedef struct IVsSqmOptinManagerVtbl
    {
        BEGIN_INTERFACE
        
        HRESULT ( STDMETHODCALLTYPE *QueryInterface )( 
            __RPC__in IVsSqmOptinManager * This,
            /* [in] */ __RPC__in REFIID riid,
            /* [annotation][iid_is][out] */ 
            _COM_Outptr_  void **ppvObject);
        
        ULONG ( STDMETHODCALLTYPE *AddRef )( 
            __RPC__in IVsSqmOptinManager * This);
        
        ULONG ( STDMETHODCALLTYPE *Release )( 
            __RPC__in IVsSqmOptinManager * This);
        
        HRESULT ( STDMETHODCALLTYPE *GetOptinStatus )( 
            __RPC__in IVsSqmOptinManager * This,
            /* [out] */ __RPC__out BOOL *pOptinStatus,
            /* [out] */ __RPC__out BOOL *pPreferences);
        
        HRESULT ( STDMETHODCALLTYPE *SetOptinStatus )( 
            __RPC__in IVsSqmOptinManager * This,
            /* [in] */ BOOL OptinStatus);
        
        END_INTERFACE
    } IVsSqmOptinManagerVtbl;

    interface IVsSqmOptinManager
    {
        CONST_VTBL struct IVsSqmOptinManagerVtbl *lpVtbl;
    };

    

#ifdef COBJMACROS


#define IVsSqmOptinManager_QueryInterface(This,riid,ppvObject)	\
    ( (This)->lpVtbl -> QueryInterface(This,riid,ppvObject) ) 

#define IVsSqmOptinManager_AddRef(This)	\
    ( (This)->lpVtbl -> AddRef(This) ) 

#define IVsSqmOptinManager_Release(This)	\
    ( (This)->lpVtbl -> Release(This) ) 


#define IVsSqmOptinManager_GetOptinStatus(This,pOptinStatus,pPreferences)	\
    ( (This)->lpVtbl -> GetOptinStatus(This,pOptinStatus,pPreferences) ) 

#define IVsSqmOptinManager_SetOptinStatus(This,OptinStatus)	\
    ( (This)->lpVtbl -> SetOptinStatus(This,OptinStatus) ) 

#endif /* COBJMACROS */


#endif 	/* C style interface */




#endif 	/* __IVsSqmOptinManager_INTERFACE_DEFINED__ */


/* interface __MIDL_itf_vslog_0000_0004 */
/* [local] */ 

#define SID_SVsLog IID_IVsLog


extern RPC_IF_HANDLE __MIDL_itf_vslog_0000_0004_v0_0_c_ifspec;
extern RPC_IF_HANDLE __MIDL_itf_vslog_0000_0004_v0_0_s_ifspec;

/* Additional Prototypes for ALL interfaces */

unsigned long             __RPC_USER  BSTR_UserSize(     __RPC__in unsigned long *, unsigned long            , __RPC__in BSTR * ); 
unsigned char * __RPC_USER  BSTR_UserMarshal(  __RPC__in unsigned long *, __RPC__inout_xcount(0) unsigned char *, __RPC__in BSTR * ); 
unsigned char * __RPC_USER  BSTR_UserUnmarshal(__RPC__in unsigned long *, __RPC__in_xcount(0) unsigned char *, __RPC__out BSTR * ); 
void                      __RPC_USER  BSTR_UserFree(     __RPC__in unsigned long *, __RPC__in BSTR * ); 

/* end of Additional Prototypes */

#ifdef __cplusplus
}
#endif

#endif


